In [1]:
import numpy as np
import pandas as pd

In [2]:
CR = pd.read_csv("train_split.csv")

In [3]:
CR.shape

(63999, 45)

In [4]:
CR

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,...,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,verification_status_joint,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36 months,,19.19,E,E3,clerk,...,0.0,74.0,INDIVIDUAL,NaN,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,...,0.0,NaN,INDIVIDUAL,NaN,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36 months,BAT1586599,7.26,A,A4,Driver,...,0.0,NaN,INDIVIDUAL,NaN,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,...,0.0,NaN,INDIVIDUAL,NaN,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,...,0.0,NaN,INDIVIDUAL,NaN,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36 months,BAT2575549,8.90,A,A5,Design Consultant,...,0.0,NaN,INDIVIDUAL,NaN,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,...,0.0,NaN,INDIVIDUAL,NaN,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36 months,NaN,9.17,B,B1,Banker,...,0.0,54.0,INDIVIDUAL,NaN,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36 months,BAT4136152,13.99,C,C4,LVN,...,0.0,NaN,INDIVIDUAL,NaN,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60 months,BAT4694572,17.14,D,D4,Registered Nurse,...,0.0,NaN,INDIVIDUAL,NaN,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36 months,,13.33,C,C3,VP of Operations,...,0.0,52.0,INDIVIDUAL,NaN,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36 months,,18.49,D,D2,Jp Morgan chase bank,...,0.0,82.0,INDIVIDUAL,NaN,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36 months,BAT5924421,6.99,A,A3,driver,...,0.0,NaN,INDIVIDUAL,NaN,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,...,0.0,NaN,INDIVIDUAL,NaN,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36 months,BAT224923,13.65,C,C1,Truck Driver,...,0.0,NaN,INDIVIDUAL,NaN,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,...,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60 months,BAT1930365,21.70,E,E2,LS1,...,0.0,72.0,INDIVIDUAL,NaN,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36 months,,16.99,D,D1,NaN,...,0.0,26.0,INDIVIDUAL,NaN,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36 months,BAT3873588,9.99,B,B3,Production employee,...,0.0,NaN,INDIVIDUAL,NaN,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36 months,NaN,10.99,B,B4,Principal Consultant,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60 months,BAT2252229,17.86,D,D5,Zone business manager,...,0.0,18.0,INDIVIDUAL,NaN,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36 months,BAT1135695,6.62,A,A2,Expeditors,...,0.0,NaN,INDIVIDUAL,NaN,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36 months,,17.57,D,D4,production coordinator,...,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36 months,BAT4694572,13.66,C,C3,Title Manager,...,0.0,NaN,INDIVIDUAL,NaN,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36 months,BAT4271519,7.89,A,A5,Coordinator,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60 months,,15.61,D,D1,Quality Engineer,...,0.0,NaN,INDIVIDUAL,NaN,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36 months,NaN,12.99,C,C1,Top shelf sales,...,0.0,47.0,INDIVIDUAL,NaN,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36 months,NaN,6.62,A,A2,Physician,...,0.0,NaN,INDIVIDUAL,NaN,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36 months,BAT1184694,6.92,A,A4,Teacher,...,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36 months,BAT1586599,17.57,D,D4,cna,...,0.0,NaN,INDIVIDUAL,NaN,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60 months,BAT1104812,18.84,E,E2,Manager,...,0.0,68.0,INDIVIDUAL,NaN,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60 months,,17.77,D,D1,ECC,...,0.0,33.0,INDIVIDUAL,NaN,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36 months,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,...,0.0,NaN,INDIVIDUAL,NaN,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60 months,BAT4271519,17.57,D,D4,Vocational Counselor,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60 months,NaN,17.57,D,D4,Securities broker,...,0.0,NaN,INDIVIDUAL,NaN,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36 months,BAT2833642,13.05,B,B5,New York Life Insurance Company,...,0.0,NaN,INDIVIDUAL,NaN,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36 months,,12.12,B,B3,Comforce Telecom,...,0.0,NaN,INDIVIDUAL,NaN,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36 months,,12.99,B,B5,Process Operator,...,0.0,57.0,INDIVIDUAL,NaN,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60 months,BAT2803411,15.41,D,D1,Vice President mortgage sales,...,0.0,NaN,INDIVIDUAL,NaN,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36 months,BAT3873588,9.17,B,B2,Nurse,...,0.0,36.0,INDIVIDUAL,NaN,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36 months,,13.35,C,C2,Nurse,...,0.0,NaN,INDIVIDUAL,NaN,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36 months,,15.61,D,D1,Patient account rep,...,0.0,8.0,INDIVIDUAL,NaN,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36 months,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,...,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36 months,BAT2558388,12.39,C,C1,Research Scientist,...,0.0,NaN,INDIVIDUAL,NaN,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36 months,NaN,15.61,D,D1,NaN,...,0.0,NaN,INDIVIDUAL,NaN,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36 months,BAT2575549,14.30,C,C1,Technical Support,...,0.0,NaN,INDIVIDUAL,NaN,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60 months,BAT1780517,13.33,C,C3,SUPERVISOR,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60 months,,23.99,F,F3,Assistant Project Director,...,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36 months,NaN,11.99,B,B3,NaN,...,0.0,NaN,INDIVIDUAL,NaN,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36 months,BAT1691418,5.99,A,A2,KELLYS HARDWARE,...,0.0,NaN,INDIVIDUAL,NaN,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36 months,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,...,0.0,NaN,INDIVIDUAL,NaN,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36 months,BAT5811547,8.90,A,A5,Creative Technology,...,0.0,NaN,INDIVIDUAL,NaN,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36 months,NaN,18.55,D,D2,Senior Estimator,...,0.0,NaN,INDIVIDUAL,NaN,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36 months,BAT1184694,15.61,D,D1,Account executive,...,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36 months,,12.39,C,C1,Payroll and billing specialist,...,0.0,17.0,INDIVIDUAL,NaN,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36 months,BAT2252229,9.99,B,B3,Manager,...,0.0,NaN,INDIVIDUAL,NaN,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36 months,BAT47674,8.90,A,A5,ATT Prime Communications,...,0.0,NaN,INDIVIDUAL,NaN,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36 months,NaN,6.24,A,A2,Account Executive,...,0.0,NaN,INDIVIDUAL,NaN,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36 months,,11.53,B,B5,Assistant instructor,...,0.0,NaN,INDIVIDUAL,NaN,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36 months,NaN,6.62,A,A2,Array Connector Corp,...,0.0,NaN,INDIVIDUAL,NaN,161th week,0,0.0,3148.0,40988.0,1

In [5]:
pd.set_option('display.max_columns',None)

In [6]:
CR

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,verification_status_joint,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36 months,,19.19,E,E3,clerk,9 years,OWN,28700.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,349xx,FL,33.88,0,1,50.0,75.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,74.0,INDIVIDUAL,NaN,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,< 1 year,MORTGAGE,65000.00,Source Verified,n,NaN,home_improvement,Home improvement,209xx,MD,3.64,0,1,NaN,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36 months,BAT1586599,7.26,A,A4,Driver,2 years,OWN,45000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,447xx,OH,18.42,0,0,NaN,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,10+ years,RENT,105000.00,Not Verified,n,> My goal is to obtain a loan to pay off my hi...,debt_consolidation,Debt consolidation,221xx,VA,14.97,0,2,46.0,NaN,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10+ years,RENT,52000.00,Verified,n,NaN,credit_card,refi,900xx,CA,20.16,0,0,NaN,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36 months,BAT2575549,8.90,A,A5,Design Consultant,2 years,MORTGAGE,120000.00,Not Verified,n,> We are requesting this loan to help re-or...,debt_consolidation,Credit Card Debt Consolidation,461xx,IN,12.30,0,0,56.0,NaN,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5 years,RENT,75000.00,Source Verified,n,> Funds will be used to pay off a debt. I am a...,debt_consolidation,PAY THEM OFF,913xx,CA,5.70,0,0,NaN,105.0,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36 months,NaN,9.17,B,B1,Banker,8 years,MORTGAGE,54000.00,Not Verified,n,NaN,credit_card,Credit card refinancing,351xx,AL,11.63,0,1,46.0,NaN,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,54.0,INDIVIDUAL,NaN,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36 months,BAT4136152,13.99,C,C4,LVN,7 years,MORTGAGE,92000.00,Not Verified,n,NaN,home_improvement,Home improvement,917xx,CA,30.85,0,0,77.0,NaN,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60 months,BAT4694572,17.14,D,D4,Registered Nurse,2 years,MORTGAGE,72000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,427xx,KY,33.92,0,0,NaN,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36 months,,13.33,C,C3,VP of Operations,10+ years,OWN,135000.00,Source Verified,n,NaN,credit_card,Credit card refinancing,875xx,NM,14.20,0,1,52.0,NaN,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,52.0,INDIVIDUAL,NaN,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36 months,,18.49,D,D2,Jp Morgan chase bank,4 years,RENT,76000.00,Verified,n,NaN,debt_consolidation,Loan to payoff credit card debt,926xx,CA,15.86,0,1,82.0,NaN,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,82.0,INDIVIDUAL,NaN,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36 months,BAT5924421,6.99,A,A3,driver,7 years,MORTGAGE,62000.00,Not Verified,n,NaN,credit_card,Credit card refinancing,381xx,TN,18.58,0,2,NaN,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,10+ years,MORTGAGE,145000.00,Not Verified,n,NaN,credit_card,Credit card refinancing,773xx,TX,15.42,0,0,NaN,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36 months,BAT224923,13.65,C,C1,Truck Driver,10+ years,RENT,80000.00,Not Verified,n,> Debt Consolidation<br>,debt_consolidation,Debt consolidation,917xx,CA,13.98,0,1,NaN,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4 years,RENT,50000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,922xx,CA,27.39,0,2,NaN,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60 months,BAT1930365,21.70,E,E2,LS1,9 years,RENT,69000.00,Source Verified,n,NaN,debt_consolidation,Debt Consolidation,919xx,CA,24.28,0,0,72.0,NaN,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,72.0,INDIVIDUAL,NaN,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36 months,,16.99,D,D1,NaN,NaN,MORTGAGE,70000.00,Verified,n,> credit card consolidation.<br><br> > this l...,credit_card,Credit card refinancing,191xx,PA,29.13,3,2,11.0,NaN,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,26.0,INDIVIDUAL,NaN,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36 months,BAT3873588,9.99,B,B3,Production employee,7 years,RENT,60000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,666xx,KS,19.70,0,0,NaN,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36 months,NaN,10.99,B,B4,Principal Consultant,7 years,RENT,130000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,606xx,IL,23.22,0,1,56.0,NaN,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60 months,BAT2252229,17.86,D,D5,Zone business manager,9 years,RENT,96000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,322xx,FL,18.31,1,0,18.0,NaN,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,18.0,INDIVIDUAL,NaN,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36 months,BAT1135695,6.62,A,A2,Expeditors,2 years,OWN,40000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,114xx,NY,20.31,0,2,28.0,NaN,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,NaN,INDIVIDUAL,NaN,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36 months,,17.57,D,D4,production coordinator,10+ years,MORTGAGE,46000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,928xx,CA,31.25,1,0,20.0,NaN,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36 months,BAT4694572,13.66,C,C3,Title Manager,7 years,OWN,60000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,631xx,MO,13.82,0,1,NaN,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36 months,BAT4271519,7.89,A,A5,Coordinator,< 1 year,RENT,65000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,337xx,FL,21.54,0,0,NaN,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60 months,,15.61,D,D1,Quality Engineer,4 years,MORTGAGE,70000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,285xx,NC,21.93,0,0,NaN,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36 months,NaN,12.99,C,C1,Top shelf sales,2 years,OWN,37000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,764xx,TX,13.43,0,0,73.0,50.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,47.0,INDIVIDUAL,NaN,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36 months,NaN,6.62,A,A2,Physician,1 year,MORTGAGE,250000.00,Source Verified,n,NaN,debt_consolidation,Close cards and consolidate,352xx,AL,25.86,0,1,NaN,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36 months,BAT1184694,6.92,A,A4,Teacher,3 years,MORTGAGE,90000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,757xx,TX,29.68,0,1,NaN,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36 months,BAT1586599,17.57,D,D4,cna,2 years,MORTGAGE,20000.00,Verified,n,NaN,other,Other,073xx,NJ,30.79,0,0,NaN,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60 months,BAT1104812,18.84,E,E2,Manager,5 years,RENT,114000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,070xx,NJ,24.56,0,2,68.0,NaN,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,68.0,INDIVIDUAL,NaN,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60 months,,17.77,D,D1,ECC,3 years,MORTGAGE,68000.00,Verified,n,NaN,debt_consolidation,Pool,015xx,MA,10.34,0,1,30.0,97.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,33.0,INDIVIDUAL,NaN,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36 months,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,< 1 year,MORTGAGE,100000.00,Not Verified,n,NaN,medical,Medical expenses,900xx,CA,3.31,0,0,NaN,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60 months,BAT4271519,17.57,D,D4,Vocational Counselor,10+ years,RENT,43008.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,631xx,MO,19.50,0,0,NaN,97.0,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60 months,NaN,17.57,D,D4,Securities broker,8 years,MORTGAGE,250000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,721xx,AR,13.18,2,1,3.0,NaN,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36 months,BAT2833642,13.05,B,B5,New York Life Insurance Company,3 years,RENT,74000.00,Verified,n,> I have a few high balance cards I want to...,debt_consolidation,Debt consolidation,107xx,NY,18.40,0,0,NaN,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36 months,,12.12,B,B3,Comforce Telecom,10+ years,MORTGAGE,63300.00,Verified,n,> I have several credit cards that I have been...,debt_consolidation,Credit Card Consolidation,342xx,FL,27.51,0,0,NaN,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36 months,,12.99,B,B5,Process Operator,7 years,MORTGAGE,80000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,478xx,IN,9.44,0,0,57.0,NaN,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,57.0,INDIVIDUAL,NaN,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60 months,BAT2803411,15.41,D,D1,Vice President mortgage sales,2 years,MORTGAGE,75000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,380xx,TN,24.21,2,2,12.0,65.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36 months,BAT3873588,9.17,B,B2,Nurse,8 years,MORTGAGE,88000.00,Not Verified,n,NaN,home_improvement,Home improvement,717xx,AR,17.52,0,1,36.0,NaN,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,36.0,INDIVIDUAL,NaN,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36 months,,13.35,C,C2,Nurse,10+ years,RENT,60000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,327xx,FL,24.68,0,0,NaN,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36 months,,15.61,D,D1,Patient account rep,8 years,MORTGAGE,43000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,554xx,MN,20.76,1,1,NaN,48.0,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,8.0,INDIVIDUAL,NaN,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36 months,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4 years,MORTGAGE,109000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,067xx,CT,10.28,0,0,NaN,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36 months,BAT2558388,12.39,C,C1,Research Scientist,4 years,RENT,71000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,921xx,CA,16.41,0,0,NaN,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36 months,NaN,15.61,D,D1,NaN,NaN,MORTGAGE,79384.56,Source Verified,n,NaN,debt_consolidation,Debt consolidation,291xx,SC,31.29,0,0,NaN,98.0,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36 months,BAT2575549,14.30,C,C1,Technical Support,< 1 year,RENT,35000.00,Verified,n,NaN,credit_card,Debt Consolidation,785xx,TX,15.22,0,2,NaN,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60 months,BAT1780517,13.33,C,C3,SUPERVISOR,1 year,RENT,55000.00,Source Verified,n,NaN,credit_card,Credit card refinancing,902xx,CA,12.46,0,0,NaN,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60 months,,23.99,F,F3,Assistant Project Director,6 years,OWN,37000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,082xx,NJ,24.78,0,1,NaN,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36 months,NaN,11.99,B,B3,NaN,9 years,RENT,65000.00,Verified,n,NaN,debt_consolidation,Bye bye Debt!,921xx,CA,7.09,0,0,79.0,NaN,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36 months,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1 year,RENT,19200.00,Not Verified,n,> need to pay off bills<br/> > paying off bil...,other,BILLS,720xx,AR,2.06,0,0,55.0,NaN,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,NaN,INDIVIDUAL,NaN,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36 months,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10+ years,MORTGAGE,101000.00,Verified,n,NaN,debt_consolidation,credit card payoff,023xx,MA,14.91,0,0,NaN,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36 months,BAT5811547,8.90,A,A5,Creative Technology,10+ years,MORTGAGE,160000.00,Source Verified,n,NaN,debt_consolidation,Get Rid Of Debt,430xx,OH,12.83,0,2,24.0,NaN,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36 months,NaN,18.55,D,D2,Senior Estimator,10+ years,RENT,40000.00,Not Verified,n,> I want to pay off my high interest cards to ...,debt_consolidation,The Great Payoff,630xx,MO,18.69,0,1,57.0,NaN,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36 months,BAT1184694,15.61,D,D1,Account executive,2 years,RENT,148000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,941xx,CA,7.07,0,0,NaN,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36 months,,12.39,C,C1,Payroll and billing specialist,2 years,RENT,40000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,606xx,IL,8.43,9,1,17.0,NaN,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,17.0,INDIVIDUAL,NaN,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36 months,BAT2252229,9.99,B,B3,Manager,< 1 year,RENT,60000.00,Source Verified,n,NaN,credit_card,Credit card refinancing,082xx,NJ,17.48,0,0,NaN,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36 months,BAT47674,8.90,A,A5,ATT Prime Communications,2 years,RENT,42000.00,Source Verified,n,> I am requesting this loan for a vehicle that...,car,Car Loan,757xx,TX,12.09,0,2,NaN,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36 months,NaN,6.24,A,A2,Account Executive,2 years,RENT,85000.00,Not Verified,n,NaN,major_purchase,Major purchase,951xx,CA,9.40,0,0,NaN,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36 months,,11.53,B,B5,Assistant instructor,3 years,RENT,27000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,070xx,NJ,18.67,0,0,NaN,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36 months,NaN,6.62,A,A2,Array Connector Corp,5 years,RENT,40000.00,Not Verified,n,NaN,home_improvement,LoanForGood_2012,331xx,FL,3.57,0,1,NaN,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,161th week,0,0.0,3148.0,40988.0,1

In [7]:
CR_copy = CR

In [8]:
CR_copy.shape

(63999, 45)

In [9]:
CR_copy.isnull().sum()

member_id                          0
loan_amnt                          0
funded_amnt                        0
funded_amnt_inv                    0
term                               0
batch_enrolled                 10264
int_rate                           0
grade                              0
sub_grade                          0
emp_title                       3826
emp_length                      3324
home_ownership                     0
annual_inc                         0
verification_status                0
pymnt_plan                         0
desc                           54849
purpose                            0
title                             13
zip_code                           0
addr_state                         0
dti                                0
delinq_2yrs                        0
inq_last_6mths                     0
mths_since_last_delinq         32831
mths_since_last_record         54349
open_acc                           0
pub_rec                            0
revol_bal                          0
revol_util                        29
total_acc                          0
initial_list_status                0
total_rec_int                      0
total_rec_late_fee                 0
recoveries                         0
collection_recovery_fee            0
collections_12_mths_ex_med         8
mths_since_last_major_derog    48155
application_type                   0
verification_status_joint      63971
last_week_pay                      0
acc_now_delinq                     0
tot_coll_amt                    5124
tot_cur_bal                     5124
total_rev_hi_lim                5124
loan_status                        0
dtype: int64

In [10]:
CR_copy

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,mths_since_last_major_derog,application_type,verification_status_joint,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36 months,,19.19,E,E3,clerk,9 years,OWN,28700.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,349xx,FL,33.88,0,1,50.0,75.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,74.0,INDIVIDUAL,NaN,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,< 1 year,MORTGAGE,65000.00,Source Verified,n,NaN,home_improvement,Home improvement,209xx,MD,3.64,0,1,NaN,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36 months,BAT1586599,7.26,A,A4,Driver,2 years,OWN,45000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,447xx,OH,18.42,0,0,NaN,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,10+ years,RENT,105000.00,Not Verified,n,> My goal is to obtain a loan to pay off my hi...,debt_consolidation,Debt consolidation,221xx,VA,14.97,0,2,46.0,NaN,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10+ years,RENT,52000.00,Verified,n,NaN,credit_card,refi,900xx,CA,20.16,0,0,NaN,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36 months,BAT2575549,8.90,A,A5,Design Consultant,2 years,MORTGAGE,120000.00,Not Verified,n,> We are requesting this loan to help re-or...,debt_consolidation,Credit Card Debt Consolidation,461xx,IN,12.30,0,0,56.0,NaN,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5 years,RENT,75000.00,Source Verified,n,> Funds will be used to pay off a debt. I am a...,debt_consolidation,PAY THEM OFF,913xx,CA,5.70,0,0,NaN,105.0,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36 months,NaN,9.17,B,B1,Banker,8 years,MORTGAGE,54000.00,Not Verified,n,NaN,credit_card,Credit card refinancing,351xx,AL,11.63,0,1,46.0,NaN,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,54.0,INDIVIDUAL,NaN,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36 months,BAT4136152,13.99,C,C4,LVN,7 years,MORTGAGE,92000.00,Not Verified,n,NaN,home_improvement,Home improvement,917xx,CA,30.85,0,0,77.0,NaN,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60 months,BAT4694572,17.14,D,D4,Registered Nurse,2 years,MORTGAGE,72000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,427xx,KY,33.92,0,0,NaN,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36 months,,13.33,C,C3,VP of Operations,10+ years,OWN,135000.00,Source Verified,n,NaN,credit_card,Credit card refinancing,875xx,NM,14.20,0,1,52.0,NaN,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,52.0,INDIVIDUAL,NaN,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36 months,,18.49,D,D2,Jp Morgan chase bank,4 years,RENT,76000.00,Verified,n,NaN,debt_consolidation,Loan to payoff credit card debt,926xx,CA,15.86,0,1,82.0,NaN,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,82.0,INDIVIDUAL,NaN,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36 months,BAT5924421,6.99,A,A3,driver,7 years,MORTGAGE,62000.00,Not Verified,n,NaN,credit_card,Credit card refinancing,381xx,TN,18.58,0,2,NaN,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,10+ years,MORTGAGE,145000.00,Not Verified,n,NaN,credit_card,Credit card refinancing,773xx,TX,15.42,0,0,NaN,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36 months,BAT224923,13.65,C,C1,Truck Driver,10+ years,RENT,80000.00,Not Verified,n,> Debt Consolidation<br>,debt_consolidation,Debt consolidation,917xx,CA,13.98,0,1,NaN,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4 years,RENT,50000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,922xx,CA,27.39,0,2,NaN,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60 months,BAT1930365,21.70,E,E2,LS1,9 years,RENT,69000.00,Source Verified,n,NaN,debt_consolidation,Debt Consolidation,919xx,CA,24.28,0,0,72.0,NaN,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,72.0,INDIVIDUAL,NaN,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36 months,,16.99,D,D1,NaN,NaN,MORTGAGE,70000.00,Verified,n,> credit card consolidation.<br><br> > this l...,credit_card,Credit card refinancing,191xx,PA,29.13,3,2,11.0,NaN,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,26.0,INDIVIDUAL,NaN,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36 months,BAT3873588,9.99,B,B3,Production employee,7 years,RENT,60000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,666xx,KS,19.70,0,0,NaN,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36 months,NaN,10.99,B,B4,Principal Consultant,7 years,RENT,130000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,606xx,IL,23.22,0,1,56.0,NaN,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60 months,BAT2252229,17.86,D,D5,Zone business manager,9 years,RENT,96000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,322xx,FL,18.31,1,0,18.0,NaN,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,18.0,INDIVIDUAL,NaN,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36 months,BAT1135695,6.62,A,A2,Expeditors,2 years,OWN,40000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,114xx,NY,20.31,0,2,28.0,NaN,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,NaN,INDIVIDUAL,NaN,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36 months,,17.57,D,D4,production coordinator,10+ years,MORTGAGE,46000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,928xx,CA,31.25,1,0,20.0,NaN,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36 months,BAT4694572,13.66,C,C3,Title Manager,7 years,OWN,60000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,631xx,MO,13.82,0,1,NaN,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36 months,BAT4271519,7.89,A,A5,Coordinator,< 1 year,RENT,65000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,337xx,FL,21.54,0,0,NaN,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60 months,,15.61,D,D1,Quality Engineer,4 years,MORTGAGE,70000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,285xx,NC,21.93,0,0,NaN,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36 months,NaN,12.99,C,C1,Top shelf sales,2 years,OWN,37000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,764xx,TX,13.43,0,0,73.0,50.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,47.0,INDIVIDUAL,NaN,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36 months,NaN,6.62,A,A2,Physician,1 year,MORTGAGE,250000.00,Source Verified,n,NaN,debt_consolidation,Close cards and consolidate,352xx,AL,25.86,0,1,NaN,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36 months,BAT1184694,6.92,A,A4,Teacher,3 years,MORTGAGE,90000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,757xx,TX,29.68,0,1,NaN,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36 months,BAT1586599,17.57,D,D4,cna,2 years,MORTGAGE,20000.00,Verified,n,NaN,other,Other,073xx,NJ,30.79,0,0,NaN,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60 months,BAT1104812,18.84,E,E2,Manager,5 years,RENT,114000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,070xx,NJ,24.56,0,2,68.0,NaN,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,68.0,INDIVIDUAL,NaN,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60 months,,17.77,D,D1,ECC,3 years,MORTGAGE,68000.00,Verified,n,NaN,debt_consolidation,Pool,015xx,MA,10.34,0,1,30.0,97.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,33.0,INDIVIDUAL,NaN,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36 months,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,< 1 year,MORTGAGE,100000.00,Not Verified,n,NaN,medical,Medical expenses,900xx,CA,3.31,0,0,NaN,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60 months,BAT4271519,17.57,D,D4,Vocational Counselor,10+ years,RENT,43008.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,631xx,MO,19.50,0,0,NaN,97.0,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60 months,NaN,17.57,D,D4,Securities broker,8 years,MORTGAGE,250000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,721xx,AR,13.18,2,1,3.0,NaN,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36 months,BAT2833642,13.05,B,B5,New York Life Insurance Company,3 years,RENT,74000.00,Verified,n,> I have a few high balance cards I want to...,debt_consolidation,Debt consolidation,107xx,NY,18.40,0,0,NaN,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36 months,,12.12,B,B3,Comforce Telecom,10+ years,MORTGAGE,63300.00,Verified,n,> I have several credit cards that I have been...,debt_consolidation,Credit Card Consolidation,342xx,FL,27.51,0,0,NaN,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36 months,,12.99,B,B5,Process Operator,7 years,MORTGAGE,80000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,478xx,IN,9.44,0,0,57.0,NaN,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,57.0,INDIVIDUAL,NaN,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60 months,BAT2803411,15.41,D,D1,Vice President mortgage sales,2 years,MORTGAGE,75000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,380xx,TN,24.21,2,2,12.0,65.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36 months,BAT3873588,9.17,B,B2,Nurse,8 years,MORTGAGE,88000.00,Not Verified,n,NaN,home_improvement,Home improvement,717xx,AR,17.52,0,1,36.0,NaN,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,36.0,INDIVIDUAL,NaN,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36 months,,13.35,C,C2,Nurse,10+ years,RENT,60000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,327xx,FL,24.68,0,0,NaN,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36 months,,15.61,D,D1,Patient account rep,8 years,MORTGAGE,43000.00,Verified,n,NaN,debt_consolidation,Debt consolidation,554xx,MN,20.76,1,1,NaN,48.0,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,8.0,INDIVIDUAL,NaN,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36 months,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4 years,MORTGAGE,109000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,067xx,CT,10.28,0,0,NaN,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36 months,BAT2558388,12.39,C,C1,Research Scientist,4 years,RENT,71000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,921xx,CA,16.41,0,0,NaN,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36 months,NaN,15.61,D,D1,NaN,NaN,MORTGAGE,79384.56,Source Verified,n,NaN,debt_consolidation,Debt consolidation,291xx,SC,31.29,0,0,NaN,98.0,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36 months,BAT2575549,14.30,C,C1,Technical Support,< 1 year,RENT,35000.00,Verified,n,NaN,credit_card,Debt Consolidation,785xx,TX,15.22,0,2,NaN,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60 months,BAT1780517,13.33,C,C3,SUPERVISOR,1 year,RENT,55000.00,Source Verified,n,NaN,credit_card,Credit card refinancing,902xx,CA,12.46,0,0,NaN,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60 months,,23.99,F,F3,Assistant Project Director,6 years,OWN,37000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,082xx,NJ,24.78,0,1,NaN,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36 months,NaN,11.99,B,B3,NaN,9 years,RENT,65000.00,Verified,n,NaN,debt_consolidation,Bye bye Debt!,921xx,CA,7.09,0,0,79.0,NaN,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36 months,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1 year,RENT,19200.00,Not Verified,n,> need to pay off bills<br/> > paying off bil...,other,BILLS,720xx,AR,2.06,0,0,55.0,NaN,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,NaN,INDIVIDUAL,NaN,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36 months,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10+ years,MORTGAGE,101000.00,Verified,n,NaN,debt_consolidation,credit card payoff,023xx,MA,14.91,0,0,NaN,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36 months,BAT5811547,8.90,A,A5,Creative Technology,10+ years,MORTGAGE,160000.00,Source Verified,n,NaN,debt_consolidation,Get Rid Of Debt,430xx,OH,12.83,0,2,24.0,NaN,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36 months,NaN,18.55,D,D2,Senior Estimator,10+ years,RENT,40000.00,Not Verified,n,> I want to pay off my high interest cards to ...,debt_consolidation,The Great Payoff,630xx,MO,18.69,0,1,57.0,NaN,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36 months,BAT1184694,15.61,D,D1,Account executive,2 years,RENT,148000.00,Source Verified,n,NaN,debt_consolidation,Debt consolidation,941xx,CA,7.07,0,0,NaN,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36 months,,12.39,C,C1,Payroll and billing specialist,2 years,RENT,40000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,606xx,IL,8.43,9,1,17.0,NaN,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,17.0,INDIVIDUAL,NaN,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36 months,BAT2252229,9.99,B,B3,Manager,< 1 year,RENT,60000.00,Source Verified,n,NaN,credit_card,Credit card refinancing,082xx,NJ,17.48,0,0,NaN,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36 months,BAT47674,8.90,A,A5,ATT Prime Communications,2 years,RENT,42000.00,Source Verified,n,> I am requesting this loan for a vehicle that...,car,Car Loan,757xx,TX,12.09,0,2,NaN,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36 months,NaN,6.24,A,A2,Account Executive,2 years,RENT,85000.00,Not Verified,n,NaN,major_purchase,Major purchase,951xx,CA,9.40,0,0,NaN,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36 months,,11.53,B,B5,Assistant instructor,3 years,RENT,27000.00,Not Verified,n,NaN,debt_consolidation,Debt consolidation,070xx,NJ,18.67,0,0,NaN,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36 months,NaN,6.62,A,A2,Array Connector Corp,5 years,RENT,40000.00,Not Verified,n,NaN,home_improvement,LoanForGood_2012,331xx,FL,3.57,0,1,NaN,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,NaN,INDIVIDUAL,NaN,161th week,0,0.0,3148.0,40988.0,1

In [11]:
CR_col_drop = CR.drop(columns=['pymnt_plan','desc','zip_code','mths_since_last_record','mths_since_last_major_derog',
                              'verification_status_joint'],axis=1)

In [12]:
CR_col_drop.shape

(63999, 39)

In [13]:
CR_col_drop.isnull().sum()

member_id                         0
loan_amnt                         0
funded_amnt                       0
funded_amnt_inv                   0
term                              0
batch_enrolled                10264
int_rate                          0
grade                             0
sub_grade                         0
emp_title                      3826
emp_length                     3324
home_ownership                    0
annual_inc                        0
verification_status               0
purpose                           0
title                            13
addr_state                        0
dti                               0
delinq_2yrs                       0
inq_last_6mths                    0
mths_since_last_delinq        32831
open_acc                          0
pub_rec                           0
revol_bal                         0
revol_util                       29
total_acc                         0
initial_list_status               0
total_rec_int                     0
total_rec_late_fee                0
recoveries                        0
collection_recovery_fee           0
collections_12_mths_ex_med        8
application_type                  0
last_week_pay                     0
acc_now_delinq                    0
tot_coll_amt                   5124
tot_cur_bal                    5124
total_rev_hi_lim               5124
loan_status                       0
dtype: int64

In [14]:
CR_col_drop.corr()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
member_id,1.000000,0.067213,0.069355,0.074639,-0.144060,0.035727,0.138130,0.057197,-0.127077,-0.014288,0.087062,0.078686,0.034260,-0.054114,0.033610,-0.464313,-0.073430,-0.117562,-0.068790,0.061426,0.018759,0.030427,0.004053,0.054620,-0.487251
loan_amnt,0.067213,1.000000,0.999367,0.997395,0.143669,0.401085,0.041609,0.000742,-0.034008,-0.036365,0.193324,-0.081700,0.341497,0.123082,0.222000,0.532376,0.030397,0.075566,0.054566,-0.015888,0.000483,-0.022103,0.334471,0.361013,-0.098061
funded_amnt,0.069355,0.999367,1.000000,0.998170,0.143793,0.400872,0.042324,0.001055,-0.034522,-0.036455,0.193525,-0.081446,0.341312,0.123443,0.221574,0.531466,0.030270,0.075439,0.054489,-0.015727,0.000584,-0.022103,0.334471,0.361013,-0.099741
funded_amnt_inv,0.074639,0.997395,0.998170,1.000000,0.143945,0.399946,0.044392,0.001532,-0.038666,-0.034672,0.194182,-0.080612,0.339649,0.123951,0.221731,0.529228,0.026987,0.073469,0.051603,-0.015297,0.000441,-0.022082,0.334484,0.361071,-0.103682
int_rate,-0.144060,0.143669,0.143793,0.143945,1.000000,-0.075681,0.157896,0.055061,0.230287,-0.024344,-0.007778,0.057029,-0.035422,0.271433,-0.033448,0.448072,0.050600,0.112532,0.069415,0.013965,0.025317,0.002568,-0.090828,-0.189765,0.001316
annual_inc,0.035727,0.401085,0.400872,0.399946,-0.075681,1.000000,-0.208605,0.055868,0.039721,-0.063327,0.156166,-0.009555,0.352906,0.041826,0.219307,0.160693,0.014179,0.006552,0.006752,-0.005112,0.022310,0.003737,0.495925,0.355508,-0.005600
dti,0.138130,0.041609,0.042324,0.044392,0.157896,-0.208605,1.000000,-0.004307,-0.016475,0.002595,0.298531,-0.044592,0.139912,0.171365,0.222043,0.016711,-0.006293,0.003465,0.003673,0.003379,0.013713,-0.028187,-0.018896,0.085665,-0.134356
delinq_2yrs,0.057197,0.000742,0.001055,0.001532,0.055061,0.055868,-0.004307,1.000000,0.020384,-0.558974,0.055503,-0.010678,-0.032439,-0.012000,0.124891,-0.002126,0.017987,-0.002323,-0.000842,0.065832,0.130130,0.005283,0.066157,-0.046099,-0.044671
inq_last_6mths,-0.127077,-0.034008,-0.034522,-0.038666,0.230287,0.039721,-0.016475,0.020384,1.000000,0.014860,0.113397,0.050195,-0.023914,-0.090961,0.136223,0.087259,0.020987,0.044809,0.036406,0.006047,-0.005410,0.019235,0.032318,0.004705,0.088513
mths_since_last_delinq,-0.014288,-0.036365,-0.036455,-0.034672,-0.024344,-0.063327,0.002595,-0.558974,0.014860,1.000000,-0.052237,0.088030,-0.026681,0.012548,-0.047775,-0.023598,-0.022418,-0.002165,-0.000131,-0.036722,-0.145894,0.027479,-0.097937,-0.037352,0.034516
open_acc,0.087062,0.193324,0.193525,0.194182,-0.007778,0.156166,0.298531,0.055503,0.113397,-0.052237,1.000000,-0.034233,0.219609,-0.151660,0.698096,0.064466,-0.007397,-0.000258,0.001599,0.011836,0.017525,0.004470,0.244442,0.371487,-0.065030
pub_rec,0.078686,-0.081700,-0.081446,-0.080612,0.057029,-0.009555,-0.044592,-0.010678,0.050195,0.088030,-0.034233,1.000000,-0.103340,-0.077895,0.008906,-0.055608,-0.014384,-0.014397,-0.006056,0.027308,0.007607,0.048453,-0.076934,-0.120268,-0.047414
revol_bal,0.034260,0.341497,0.341312,0.339649,-0.035422,0.352906,0.139912,-0.032439,-0.023914,-0.026681,0.219609,-0.103340,1.000000,0.217391,0.182157,0.144990,0.003474,0.009779,0.006674,-0.026886,0.000185,-0.032536,0.450770,0.844372,-0.041665
revol_util,-0.054114,0.123082,0.123443,0.123951,0.271433,0.041826,0.171365,-0.012000,-0.090961,0.012548,-0.151660,-0.077895,0.217391,1.000000,-0.118318,0.183014,0.016914,0.033307,0.021125,-0.038334,-0.028519,-0.045412,0.083510,-0.139603,-0.047682
total_acc,0.033610,0.222000,0.221574,0.221731,-0.033448,0.219307,0.222043,0.124891,0.136223,-0.047775,0.698096,0.008906,0.182157,-0.118318,1.000000,0.094513,-0.004426,0.008568,0.007105,0.010017,0.024299,0.035683,0.309961,0.289962,-0.002207
total_rec_int,-0.464313,0.532376,0.531466,0.529228,0.448072,0.160693,0.016711,-0.002126,0.087259,-0.023598,0.064466,-0.055608,0.144990,0.183014,0.094513,1.000000,0.085284,0.072807,0.058495,-0.029296,0.000151,-0.021853,0.140847,0.088088,0.038048
total_rec_late_fee,-0.073430,0.030397,0.030270,0.026987,0.050600,0.014179,-0.006293,0.017987,0.020987,-0.022418,-0.007397,-0.014384,0.003474,0.016914,-0.004426,0.085284,1.000000,0.086066,0.063989,-0.006114,0.004883,-0.005222,0.008876,-0.003510,-0.002616
recoveries,-0.117562,0.075566,0.075439,0.073469,0.112532,0.006552,0.003465,-0.002323,0.044809,-0.002165,-0.000258,-0.014397,0.009779,0.033307,0.008568,0.072807,0.086066,1.000000,0.798005,-0.001602,-0.000229,-0.008404,-0.002086,0.001787,-0.064841
collection_recovery_fee,-0.068790,0.054566,0.054489,0.051603,0.069415,0.006752,0.003673,-0.000842,0.036406,-0.000131,0.001599,-0.006056,0.006674,0.021125,0.007105,0.058495,0.063989,0.798005,1.000000,0.002666,-0.002099,-0.005574,0.002043,0.003564,-0.041199
collections_12_mths_ex_med,0.061426,-0.015888,-0.015727,-0.015297,0.013965,-0.005112,0.003379,0.065832,0.006047,-0.036722,0.011836,0.027308,-0.026886,-0.038334,0.010017,-0.029296,-0.006114,-0.001602,0.002666,1.000000,0.017389,0.056840,-0.015485,-0.023415,-0.036779
acc_now_delinq,0.018759,0.000483,0.000584,0.000441,0.025317,0.022310,0.013713,0.130130,-0.005410,-0.145894,0.017525,0.007607,0.000185,-0.028519,0.024299,0.000151,0.004883,-0.000229,-0.002099,0.017389,1.000000,-0.000575,0.025539,0.009822,-0.013868
tot_coll_amt,0.030427,-0.022103,-0.022103,-0.022082,0.002568,0.003737,-0.028187,0.005283,0.019235,0.027479,0.004470,0.048453,-0.032536,-0.045412,0.035683,-0.021853,-0.005222,-0.008404,-0.005574,0.056840,-0.000575,1.000000,0.000432,-0.032863,-0.010139
tot_cur_bal,0.004053,0.334471,0.334471,0.334484,-0.090828,0.495925,-0.018896,0.066157,0.032318,-0.097937,0.244442,-0.076934,0.450770,0.083510,0.309961,0.140847,0.008876,-0.002086,0.002043,-0.015485,0.025539,0.000432,1.000000,0.427563,0.018390
total_rev_hi_lim,0.054620,0.361013,0.361013,0.361071,-0.189765,0.355508,0.085665,-0.046099,0.004705,-0.037352,0.371487,-0.120268,0.844372,-0.139603,0.289962,0.088088,-0.003510,0.001787,0.003564,-0.023415,0.009822,-0.032863,0.427563,1.000000,-0.027115
loan_status,-0.487251,-0.098061,-0.099741,-0.103682,0.001316,-0.005600,-0.134356,-0.044671,0.088513,0.034516,-0.065030,-0.047414,-0.041665,-0.047682,-0.002207,0.038048,-0.002616,-0.064841,-0.041199,-0.036779,-0.013868,-0.010139,0.018390,-0.027115,1.000000

In [15]:
CR_col_drop

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36 months,,19.19,E,E3,clerk,9 years,OWN,28700.00,Source Verified,debt_consolidation,Debt consolidation,FL,33.88,0,1,50.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,< 1 year,MORTGAGE,65000.00,Source Verified,home_improvement,Home improvement,MD,3.64,0,1,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36 months,BAT1586599,7.26,A,A4,Driver,2 years,OWN,45000.00,Not Verified,debt_consolidation,Debt consolidation,OH,18.42,0,0,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,10+ years,RENT,105000.00,Not Verified,debt_consolidation,Debt consolidation,VA,14.97,0,2,46.0,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10+ years,RENT,52000.00,Verified,credit_card,refi,CA,20.16,0,0,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36 months,BAT2575549,8.90,A,A5,Design Consultant,2 years,MORTGAGE,120000.00,Not Verified,debt_consolidation,Credit Card Debt Consolidation,IN,12.30,0,0,56.0,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5 years,RENT,75000.00,Source Verified,debt_consolidation,PAY THEM OFF,CA,5.70,0,0,NaN,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36 months,NaN,9.17,B,B1,Banker,8 years,MORTGAGE,54000.00,Not Verified,credit_card,Credit card refinancing,AL,11.63,0,1,46.0,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36 months,BAT4136152,13.99,C,C4,LVN,7 years,MORTGAGE,92000.00,Not Verified,home_improvement,Home improvement,CA,30.85,0,0,77.0,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60 months,BAT4694572,17.14,D,D4,Registered Nurse,2 years,MORTGAGE,72000.00,Verified,debt_consolidation,Debt consolidation,KY,33.92,0,0,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36 months,,13.33,C,C3,VP of Operations,10+ years,OWN,135000.00,Source Verified,credit_card,Credit card refinancing,NM,14.20,0,1,52.0,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36 months,,18.49,D,D2,Jp Morgan chase bank,4 years,RENT,76000.00,Verified,debt_consolidation,Loan to payoff credit card debt,CA,15.86,0,1,82.0,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36 months,BAT5924421,6.99,A,A3,driver,7 years,MORTGAGE,62000.00,Not Verified,credit_card,Credit card refinancing,TN,18.58,0,2,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,10+ years,MORTGAGE,145000.00,Not Verified,credit_card,Credit card refinancing,TX,15.42,0,0,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36 months,BAT224923,13.65,C,C1,Truck Driver,10+ years,RENT,80000.00,Not Verified,debt_consolidation,Debt consolidation,CA,13.98,0,1,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4 years,RENT,50000.00,Source Verified,debt_consolidation,Debt consolidation,CA,27.39,0,2,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60 months,BAT1930365,21.70,E,E2,LS1,9 years,RENT,69000.00,Source Verified,debt_consolidation,Debt Consolidation,CA,24.28,0,0,72.0,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36 months,,16.99,D,D1,NaN,NaN,MORTGAGE,70000.00,Verified,credit_card,Credit card refinancing,PA,29.13,3,2,11.0,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36 months,BAT3873588,9.99,B,B3,Production employee,7 years,RENT,60000.00,Source Verified,debt_consolidation,Debt consolidation,KS,19.70,0,0,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36 months,NaN,10.99,B,B4,Principal Consultant,7 years,RENT,130000.00,Verified,debt_consolidation,Debt consolidation,IL,23.22,0,1,56.0,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60 months,BAT2252229,17.86,D,D5,Zone business manager,9 years,RENT,96000.00,Not Verified,debt_consolidation,Debt consolidation,FL,18.31,1,0,18.0,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36 months,BAT1135695,6.62,A,A2,Expeditors,2 years,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36 months,,17.57,D,D4,production coordinator,10+ years,MORTGAGE,46000.00,Not Verified,debt_consolidation,Debt consolidation,CA,31.25,1,0,20.0,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36 months,BAT4694572,13.66,C,C3,Title Manager,7 years,OWN,60000.00,Source Verified,debt_consolidation,Debt consolidation,MO,13.82,0,1,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36 months,BAT4271519,7.89,A,A5,Coordinator,< 1 year,RENT,65000.00,Source Verified,debt_consolidation,Debt consolidation,FL,21.54,0,0,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60 months,,15.61,D,D1,Quality Engineer,4 years,MORTGAGE,70000.00,Source Verified,debt_consolidation,Debt consolidation,NC,21.93,0,0,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36 months,NaN,12.99,C,C1,Top shelf sales,2 years,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,TX,13.43,0,0,73.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36 months,NaN,6.62,A,A2,Physician,1 year,MORTGAGE,250000.00,Source Verified,debt_consolidation,Close cards and consolidate,AL,25.86,0,1,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36 months,BAT1184694,6.92,A,A4,Teacher,3 years,MORTGAGE,90000.00,Verified,debt_consolidation,Debt consolidation,TX,29.68,0,1,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36 months,BAT1586599,17.57,D,D4,cna,2 years,MORTGAGE,20000.00,Verified,other,Other,NJ,30.79,0,0,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60 months,BAT1104812,18.84,E,E2,Manager,5 years,RENT,114000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.56,0,2,68.0,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60 months,,17.77,D,D1,ECC,3 years,MORTGAGE,68000.00,Verified,debt_consolidation,Pool,MA,10.34,0,1,30.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36 months,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,< 1 year,MORTGAGE,100000.00,Not Verified,medical,Medical expenses,CA,3.31,0,0,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60 months,BAT4271519,17.57,D,D4,Vocational Counselor,10+ years,RENT,43008.00,Not Verified,debt_consolidation,Debt consolidation,MO,19.50,0,0,NaN,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60 months,NaN,17.57,D,D4,Securities broker,8 years,MORTGAGE,250000.00,Source Verified,debt_consolidation,Debt consolidation,AR,13.18,2,1,3.0,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36 months,BAT2833642,13.05,B,B5,New York Life Insurance Company,3 years,RENT,74000.00,Verified,debt_consolidation,Debt consolidation,NY,18.40,0,0,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36 months,,12.12,B,B3,Comforce Telecom,10+ years,MORTGAGE,63300.00,Verified,debt_consolidation,Credit Card Consolidation,FL,27.51,0,0,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36 months,,12.99,B,B5,Process Operator,7 years,MORTGAGE,80000.00,Source Verified,debt_consolidation,Debt consolidation,IN,9.44,0,0,57.0,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60 months,BAT2803411,15.41,D,D1,Vice President mortgage sales,2 years,MORTGAGE,75000.00,Source Verified,debt_consolidation,Debt consolidation,TN,24.21,2,2,12.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36 months,BAT3873588,9.17,B,B2,Nurse,8 years,MORTGAGE,88000.00,Not Verified,home_improvement,Home improvement,AR,17.52,0,1,36.0,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36 months,,13.35,C,C2,Nurse,10+ years,RENT,60000.00,Not Verified,debt_consolidation,Debt consolidation,FL,24.68,0,0,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36 months,,15.61,D,D1,Patient account rep,8 years,MORTGAGE,43000.00,Verified,debt_consolidation,Debt consolidation,MN,20.76,1,1,NaN,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36 months,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4 years,MORTGAGE,109000.00,Not Verified,debt_consolidation,Debt consolidation,CT,10.28,0,0,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36 months,BAT2558388,12.39,C,C1,Research Scientist,4 years,RENT,71000.00,Not Verified,debt_consolidation,Debt consolidation,CA,16.41,0,0,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36 months,NaN,15.61,D,D1,NaN,NaN,MORTGAGE,79384.56,Source Verified,debt_consolidation,Debt consolidation,SC,31.29,0,0,NaN,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36 months,BAT2575549,14.30,C,C1,Technical Support,< 1 year,RENT,35000.00,Verified,credit_card,Debt Consolidation,TX,15.22,0,2,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60 months,BAT1780517,13.33,C,C3,SUPERVISOR,1 year,RENT,55000.00,Source Verified,credit_card,Credit card refinancing,CA,12.46,0,0,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60 months,,23.99,F,F3,Assistant Project Director,6 years,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.78,0,1,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36 months,NaN,11.99,B,B3,NaN,9 years,RENT,65000.00,Verified,debt_consolidation,Bye bye Debt!,CA,7.09,0,0,79.0,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,INDIVIDUAL,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36 months,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1 year,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36 months,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10+ years,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36 months,BAT5811547,8.90,A,A5,Creative Technology,10+ years,MORTGAGE,160000.00,Source Verified,debt_consolidation,Get Rid Of Debt,OH,12.83,0,2,24.0,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36 months,NaN,18.55,D,D2,Senior Estimator,10+ years,RENT,40000.00,Not Verified,debt_consolidation,The Great Payoff,MO,18.69,0,1,57.0,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36 months,BAT1184694,15.61,D,D1,Account executive,2 years,RENT,148000.00,Source Verified,debt_consolidation,Debt consolidation,CA,7.07,0,0,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36 months,,12.39,C,C1,Payroll and billing specialist,2 years,RENT,40000.00,Not Verified,debt_consolidation,Debt consolidation,IL,8.43,9,1,17.0,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36 months,BAT2252229,9.99,B,B3,Manager,< 1 year,RENT,60000.00,Source Verified,credit_card,Credit card refinancing,NJ,17.48,0,0,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36 months,BAT47674,8.90,A,A5,ATT Prime Communications,2 years,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36 months,NaN,6.24,A,A2,Account Executive,2 years,RENT,85000.00,Not Verified,major_purchase,Major purchase,CA,9.40,0,0,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,INDIVIDUAL,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36 months,,11.53,B,B5,Assistant instructor,3 years,RENT,27000.00,Not Verified,debt_consolidation,Debt consolidation,NJ,18.67,0,0,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36 months,NaN,6.62,A,A2,Array Connector Corp,5 years,RENT,40000.00,Not Verified,home_improvement,LoanForGood_2012,FL,3.57,0,1,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,3148.0,40988.0,1

In [16]:
df = CR_col_drop

In [17]:
df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36 months,,19.19,E,E3,clerk,9 years,OWN,28700.00,Source Verified,debt_consolidation,Debt consolidation,FL,33.88,0,1,50.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,< 1 year,MORTGAGE,65000.00,Source Verified,home_improvement,Home improvement,MD,3.64,0,1,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36 months,BAT1586599,7.26,A,A4,Driver,2 years,OWN,45000.00,Not Verified,debt_consolidation,Debt consolidation,OH,18.42,0,0,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,10+ years,RENT,105000.00,Not Verified,debt_consolidation,Debt consolidation,VA,14.97,0,2,46.0,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10+ years,RENT,52000.00,Verified,credit_card,refi,CA,20.16,0,0,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36 months,BAT2575549,8.90,A,A5,Design Consultant,2 years,MORTGAGE,120000.00,Not Verified,debt_consolidation,Credit Card Debt Consolidation,IN,12.30,0,0,56.0,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5 years,RENT,75000.00,Source Verified,debt_consolidation,PAY THEM OFF,CA,5.70,0,0,NaN,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36 months,NaN,9.17,B,B1,Banker,8 years,MORTGAGE,54000.00,Not Verified,credit_card,Credit card refinancing,AL,11.63,0,1,46.0,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36 months,BAT4136152,13.99,C,C4,LVN,7 years,MORTGAGE,92000.00,Not Verified,home_improvement,Home improvement,CA,30.85,0,0,77.0,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60 months,BAT4694572,17.14,D,D4,Registered Nurse,2 years,MORTGAGE,72000.00,Verified,debt_consolidation,Debt consolidation,KY,33.92,0,0,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36 months,,13.33,C,C3,VP of Operations,10+ years,OWN,135000.00,Source Verified,credit_card,Credit card refinancing,NM,14.20,0,1,52.0,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36 months,,18.49,D,D2,Jp Morgan chase bank,4 years,RENT,76000.00,Verified,debt_consolidation,Loan to payoff credit card debt,CA,15.86,0,1,82.0,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36 months,BAT5924421,6.99,A,A3,driver,7 years,MORTGAGE,62000.00,Not Verified,credit_card,Credit card refinancing,TN,18.58,0,2,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,10+ years,MORTGAGE,145000.00,Not Verified,credit_card,Credit card refinancing,TX,15.42,0,0,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36 months,BAT224923,13.65,C,C1,Truck Driver,10+ years,RENT,80000.00,Not Verified,debt_consolidation,Debt consolidation,CA,13.98,0,1,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4 years,RENT,50000.00,Source Verified,debt_consolidation,Debt consolidation,CA,27.39,0,2,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60 months,BAT1930365,21.70,E,E2,LS1,9 years,RENT,69000.00,Source Verified,debt_consolidation,Debt Consolidation,CA,24.28,0,0,72.0,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36 months,,16.99,D,D1,NaN,NaN,MORTGAGE,70000.00,Verified,credit_card,Credit card refinancing,PA,29.13,3,2,11.0,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36 months,BAT3873588,9.99,B,B3,Production employee,7 years,RENT,60000.00,Source Verified,debt_consolidation,Debt consolidation,KS,19.70,0,0,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36 months,NaN,10.99,B,B4,Principal Consultant,7 years,RENT,130000.00,Verified,debt_consolidation,Debt consolidation,IL,23.22,0,1,56.0,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60 months,BAT2252229,17.86,D,D5,Zone business manager,9 years,RENT,96000.00,Not Verified,debt_consolidation,Debt consolidation,FL,18.31,1,0,18.0,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36 months,BAT1135695,6.62,A,A2,Expeditors,2 years,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36 months,,17.57,D,D4,production coordinator,10+ years,MORTGAGE,46000.00,Not Verified,debt_consolidation,Debt consolidation,CA,31.25,1,0,20.0,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36 months,BAT4694572,13.66,C,C3,Title Manager,7 years,OWN,60000.00,Source Verified,debt_consolidation,Debt consolidation,MO,13.82,0,1,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36 months,BAT4271519,7.89,A,A5,Coordinator,< 1 year,RENT,65000.00,Source Verified,debt_consolidation,Debt consolidation,FL,21.54,0,0,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60 months,,15.61,D,D1,Quality Engineer,4 years,MORTGAGE,70000.00,Source Verified,debt_consolidation,Debt consolidation,NC,21.93,0,0,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36 months,NaN,12.99,C,C1,Top shelf sales,2 years,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,TX,13.43,0,0,73.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36 months,NaN,6.62,A,A2,Physician,1 year,MORTGAGE,250000.00,Source Verified,debt_consolidation,Close cards and consolidate,AL,25.86,0,1,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36 months,BAT1184694,6.92,A,A4,Teacher,3 years,MORTGAGE,90000.00,Verified,debt_consolidation,Debt consolidation,TX,29.68,0,1,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36 months,BAT1586599,17.57,D,D4,cna,2 years,MORTGAGE,20000.00,Verified,other,Other,NJ,30.79,0,0,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60 months,BAT1104812,18.84,E,E2,Manager,5 years,RENT,114000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.56,0,2,68.0,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60 months,,17.77,D,D1,ECC,3 years,MORTGAGE,68000.00,Verified,debt_consolidation,Pool,MA,10.34,0,1,30.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36 months,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,< 1 year,MORTGAGE,100000.00,Not Verified,medical,Medical expenses,CA,3.31,0,0,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60 months,BAT4271519,17.57,D,D4,Vocational Counselor,10+ years,RENT,43008.00,Not Verified,debt_consolidation,Debt consolidation,MO,19.50,0,0,NaN,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60 months,NaN,17.57,D,D4,Securities broker,8 years,MORTGAGE,250000.00,Source Verified,debt_consolidation,Debt consolidation,AR,13.18,2,1,3.0,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36 months,BAT2833642,13.05,B,B5,New York Life Insurance Company,3 years,RENT,74000.00,Verified,debt_consolidation,Debt consolidation,NY,18.40,0,0,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36 months,,12.12,B,B3,Comforce Telecom,10+ years,MORTGAGE,63300.00,Verified,debt_consolidation,Credit Card Consolidation,FL,27.51,0,0,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36 months,,12.99,B,B5,Process Operator,7 years,MORTGAGE,80000.00,Source Verified,debt_consolidation,Debt consolidation,IN,9.44,0,0,57.0,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60 months,BAT2803411,15.41,D,D1,Vice President mortgage sales,2 years,MORTGAGE,75000.00,Source Verified,debt_consolidation,Debt consolidation,TN,24.21,2,2,12.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36 months,BAT3873588,9.17,B,B2,Nurse,8 years,MORTGAGE,88000.00,Not Verified,home_improvement,Home improvement,AR,17.52,0,1,36.0,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36 months,,13.35,C,C2,Nurse,10+ years,RENT,60000.00,Not Verified,debt_consolidation,Debt consolidation,FL,24.68,0,0,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36 months,,15.61,D,D1,Patient account rep,8 years,MORTGAGE,43000.00,Verified,debt_consolidation,Debt consolidation,MN,20.76,1,1,NaN,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36 months,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4 years,MORTGAGE,109000.00,Not Verified,debt_consolidation,Debt consolidation,CT,10.28,0,0,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36 months,BAT2558388,12.39,C,C1,Research Scientist,4 years,RENT,71000.00,Not Verified,debt_consolidation,Debt consolidation,CA,16.41,0,0,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36 months,NaN,15.61,D,D1,NaN,NaN,MORTGAGE,79384.56,Source Verified,debt_consolidation,Debt consolidation,SC,31.29,0,0,NaN,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36 months,BAT2575549,14.30,C,C1,Technical Support,< 1 year,RENT,35000.00,Verified,credit_card,Debt Consolidation,TX,15.22,0,2,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60 months,BAT1780517,13.33,C,C3,SUPERVISOR,1 year,RENT,55000.00,Source Verified,credit_card,Credit card refinancing,CA,12.46,0,0,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60 months,,23.99,F,F3,Assistant Project Director,6 years,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.78,0,1,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36 months,NaN,11.99,B,B3,NaN,9 years,RENT,65000.00,Verified,debt_consolidation,Bye bye Debt!,CA,7.09,0,0,79.0,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,INDIVIDUAL,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36 months,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1 year,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36 months,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10+ years,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36 months,BAT5811547,8.90,A,A5,Creative Technology,10+ years,MORTGAGE,160000.00,Source Verified,debt_consolidation,Get Rid Of Debt,OH,12.83,0,2,24.0,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36 months,NaN,18.55,D,D2,Senior Estimator,10+ years,RENT,40000.00,Not Verified,debt_consolidation,The Great Payoff,MO,18.69,0,1,57.0,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36 months,BAT1184694,15.61,D,D1,Account executive,2 years,RENT,148000.00,Source Verified,debt_consolidation,Debt consolidation,CA,7.07,0,0,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36 months,,12.39,C,C1,Payroll and billing specialist,2 years,RENT,40000.00,Not Verified,debt_consolidation,Debt consolidation,IL,8.43,9,1,17.0,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36 months,BAT2252229,9.99,B,B3,Manager,< 1 year,RENT,60000.00,Source Verified,credit_card,Credit card refinancing,NJ,17.48,0,0,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36 months,BAT47674,8.90,A,A5,ATT Prime Communications,2 years,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36 months,NaN,6.24,A,A2,Account Executive,2 years,RENT,85000.00,Not Verified,major_purchase,Major purchase,CA,9.40,0,0,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,INDIVIDUAL,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36 months,,11.53,B,B5,Assistant instructor,3 years,RENT,27000.00,Not Verified,debt_consolidation,Debt consolidation,NJ,18.67,0,0,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36 months,NaN,6.62,A,A2,Array Connector Corp,5 years,RENT,40000.00,Not Verified,home_improvement,LoanForGood_2012,FL,3.57,0,1,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,3148.0,40988.0,1

In [25]:
li=[]
for j in df['emp_length']:
    i = str(j)
    a = i.replace(' ','')
    b = a.replace('years','')
    c= b.replace('year','')
    d = c.replace('<','')
    li.append((d))

In [26]:
len(li)

63999

In [27]:
df_exp=df[df['emp_length']=='10+']

In [28]:
df['emp_length']=li

In [29]:
df['emp_length'].value_counts()

10+    20967
1       9175
2       5697
3       4979
5       4021
4       3760
nan     3324
7       3286
8       3179
6       3121
9       2490
Name: emp_length, dtype: int64

In [30]:
df_exp['annual_inc'].max()

3964280.0

In [31]:
df_exp['annual_inc'].min()

10000.0

# REPLACE YEARS BASED ON INCOME

# 10000 to 50000---> 10 
# 50000 to 100000---> 15
# 100000 to 200000---> 20
# 200000 to 300000---> 25
# 300000 to 400000---> 30

In [32]:
mask = (df['emp_length'] == '10+') & ((df['annual_inc'] >= 10000) & (df['annual_inc'] < 500000))
df['emp_length'][mask] = 10

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [33]:
mask = (df['emp_length'] == '10+') & ((df['annual_inc'] >= 500000) & (df['annual_inc'] < 1000000))
df['emp_length'][mask] = 15

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [34]:
mask = (df['emp_length'] == '10+') & ((df['annual_inc'] >= 1000000) & (df['annual_inc'] < 2000000))
df['emp_length'][mask] = 20

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [35]:
mask = (df['emp_length'] == '10+') & ((df['annual_inc'] >= 2000000) & (df['annual_inc'] < 3000000))
df['emp_length'][mask] = 25

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [36]:
mask = (df['emp_length'] == '10+') & ((df['annual_inc'] >= 3000000) & (df['annual_inc'] < 4000000))
df['emp_length'][mask] = 30

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [37]:
df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36 months,,19.19,E,E3,clerk,9,OWN,28700.00,Source Verified,debt_consolidation,Debt consolidation,FL,33.88,0,1,50.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,1,MORTGAGE,65000.00,Source Verified,home_improvement,Home improvement,MD,3.64,0,1,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36 months,BAT1586599,7.26,A,A4,Driver,2,OWN,45000.00,Not Verified,debt_consolidation,Debt consolidation,OH,18.42,0,0,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,10,RENT,105000.00,Not Verified,debt_consolidation,Debt consolidation,VA,14.97,0,2,46.0,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10,RENT,52000.00,Verified,credit_card,refi,CA,20.16,0,0,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36 months,BAT2575549,8.90,A,A5,Design Consultant,2,MORTGAGE,120000.00,Not Verified,debt_consolidation,Credit Card Debt Consolidation,IN,12.30,0,0,56.0,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5,RENT,75000.00,Source Verified,debt_consolidation,PAY THEM OFF,CA,5.70,0,0,NaN,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36 months,NaN,9.17,B,B1,Banker,8,MORTGAGE,54000.00,Not Verified,credit_card,Credit card refinancing,AL,11.63,0,1,46.0,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36 months,BAT4136152,13.99,C,C4,LVN,7,MORTGAGE,92000.00,Not Verified,home_improvement,Home improvement,CA,30.85,0,0,77.0,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60 months,BAT4694572,17.14,D,D4,Registered Nurse,2,MORTGAGE,72000.00,Verified,debt_consolidation,Debt consolidation,KY,33.92,0,0,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36 months,,13.33,C,C3,VP of Operations,10,OWN,135000.00,Source Verified,credit_card,Credit card refinancing,NM,14.20,0,1,52.0,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36 months,,18.49,D,D2,Jp Morgan chase bank,4,RENT,76000.00,Verified,debt_consolidation,Loan to payoff credit card debt,CA,15.86,0,1,82.0,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36 months,BAT5924421,6.99,A,A3,driver,7,MORTGAGE,62000.00,Not Verified,credit_card,Credit card refinancing,TN,18.58,0,2,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,10,MORTGAGE,145000.00,Not Verified,credit_card,Credit card refinancing,TX,15.42,0,0,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36 months,BAT224923,13.65,C,C1,Truck Driver,10,RENT,80000.00,Not Verified,debt_consolidation,Debt consolidation,CA,13.98,0,1,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4,RENT,50000.00,Source Verified,debt_consolidation,Debt consolidation,CA,27.39,0,2,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60 months,BAT1930365,21.70,E,E2,LS1,9,RENT,69000.00,Source Verified,debt_consolidation,Debt Consolidation,CA,24.28,0,0,72.0,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36 months,,16.99,D,D1,NaN,nan,MORTGAGE,70000.00,Verified,credit_card,Credit card refinancing,PA,29.13,3,2,11.0,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36 months,BAT3873588,9.99,B,B3,Production employee,7,RENT,60000.00,Source Verified,debt_consolidation,Debt consolidation,KS,19.70,0,0,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36 months,NaN,10.99,B,B4,Principal Consultant,7,RENT,130000.00,Verified,debt_consolidation,Debt consolidation,IL,23.22,0,1,56.0,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60 months,BAT2252229,17.86,D,D5,Zone business manager,9,RENT,96000.00,Not Verified,debt_consolidation,Debt consolidation,FL,18.31,1,0,18.0,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36 months,BAT1135695,6.62,A,A2,Expeditors,2,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36 months,,17.57,D,D4,production coordinator,10,MORTGAGE,46000.00,Not Verified,debt_consolidation,Debt consolidation,CA,31.25,1,0,20.0,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36 months,BAT4694572,13.66,C,C3,Title Manager,7,OWN,60000.00,Source Verified,debt_consolidation,Debt consolidation,MO,13.82,0,1,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36 months,BAT4271519,7.89,A,A5,Coordinator,1,RENT,65000.00,Source Verified,debt_consolidation,Debt consolidation,FL,21.54,0,0,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60 months,,15.61,D,D1,Quality Engineer,4,MORTGAGE,70000.00,Source Verified,debt_consolidation,Debt consolidation,NC,21.93,0,0,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36 months,NaN,12.99,C,C1,Top shelf sales,2,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,TX,13.43,0,0,73.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36 months,NaN,6.62,A,A2,Physician,1,MORTGAGE,250000.00,Source Verified,debt_consolidation,Close cards and consolidate,AL,25.86,0,1,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36 months,BAT1184694,6.92,A,A4,Teacher,3,MORTGAGE,90000.00,Verified,debt_consolidation,Debt consolidation,TX,29.68,0,1,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36 months,BAT1586599,17.57,D,D4,cna,2,MORTGAGE,20000.00,Verified,other,Other,NJ,30.79,0,0,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60 months,BAT1104812,18.84,E,E2,Manager,5,RENT,114000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.56,0,2,68.0,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60 months,,17.77,D,D1,ECC,3,MORTGAGE,68000.00,Verified,debt_consolidation,Pool,MA,10.34,0,1,30.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36 months,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,1,MORTGAGE,100000.00,Not Verified,medical,Medical expenses,CA,3.31,0,0,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60 months,BAT4271519,17.57,D,D4,Vocational Counselor,10,RENT,43008.00,Not Verified,debt_consolidation,Debt consolidation,MO,19.50,0,0,NaN,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60 months,NaN,17.57,D,D4,Securities broker,8,MORTGAGE,250000.00,Source Verified,debt_consolidation,Debt consolidation,AR,13.18,2,1,3.0,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36 months,BAT2833642,13.05,B,B5,New York Life Insurance Company,3,RENT,74000.00,Verified,debt_consolidation,Debt consolidation,NY,18.40,0,0,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36 months,,12.12,B,B3,Comforce Telecom,10,MORTGAGE,63300.00,Verified,debt_consolidation,Credit Card Consolidation,FL,27.51,0,0,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36 months,,12.99,B,B5,Process Operator,7,MORTGAGE,80000.00,Source Verified,debt_consolidation,Debt consolidation,IN,9.44,0,0,57.0,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60 months,BAT2803411,15.41,D,D1,Vice President mortgage sales,2,MORTGAGE,75000.00,Source Verified,debt_consolidation,Debt consolidation,TN,24.21,2,2,12.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36 months,BAT3873588,9.17,B,B2,Nurse,8,MORTGAGE,88000.00,Not Verified,home_improvement,Home improvement,AR,17.52,0,1,36.0,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36 months,,13.35,C,C2,Nurse,10,RENT,60000.00,Not Verified,debt_consolidation,Debt consolidation,FL,24.68,0,0,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36 months,,15.61,D,D1,Patient account rep,8,MORTGAGE,43000.00,Verified,debt_consolidation,Debt consolidation,MN,20.76,1,1,NaN,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36 months,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4,MORTGAGE,109000.00,Not Verified,debt_consolidation,Debt consolidation,CT,10.28,0,0,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36 months,BAT2558388,12.39,C,C1,Research Scientist,4,RENT,71000.00,Not Verified,debt_consolidation,Debt consolidation,CA,16.41,0,0,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36 months,NaN,15.61,D,D1,NaN,nan,MORTGAGE,79384.56,Source Verified,debt_consolidation,Debt consolidation,SC,31.29,0,0,NaN,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36 months,BAT2575549,14.30,C,C1,Technical Support,1,RENT,35000.00,Verified,credit_card,Debt Consolidation,TX,15.22,0,2,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60 months,BAT1780517,13.33,C,C3,SUPERVISOR,1,RENT,55000.00,Source Verified,credit_card,Credit card refinancing,CA,12.46,0,0,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60 months,,23.99,F,F3,Assistant Project Director,6,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.78,0,1,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36 months,NaN,11.99,B,B3,NaN,9,RENT,65000.00,Verified,debt_consolidation,Bye bye Debt!,CA,7.09,0,0,79.0,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,INDIVIDUAL,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36 months,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36 months,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36 months,BAT5811547,8.90,A,A5,Creative Technology,10,MORTGAGE,160000.00,Source Verified,debt_consolidation,Get Rid Of Debt,OH,12.83,0,2,24.0,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36 months,NaN,18.55,D,D2,Senior Estimator,10,RENT,40000.00,Not Verified,debt_consolidation,The Great Payoff,MO,18.69,0,1,57.0,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36 months,BAT1184694,15.61,D,D1,Account executive,2,RENT,148000.00,Source Verified,debt_consolidation,Debt consolidation,CA,7.07,0,0,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36 months,,12.39,C,C1,Payroll and billing specialist,2,RENT,40000.00,Not Verified,debt_consolidation,Debt consolidation,IL,8.43,9,1,17.0,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36 months,BAT2252229,9.99,B,B3,Manager,1,RENT,60000.00,Source Verified,credit_card,Credit card refinancing,NJ,17.48,0,0,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36 months,BAT47674,8.90,A,A5,ATT Prime Communications,2,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36 months,NaN,6.24,A,A2,Account Executive,2,RENT,85000.00,Not Verified,major_purchase,Major purchase,CA,9.40,0,0,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,INDIVIDUAL,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36 months,,11.53,B,B5,Assistant instructor,3,RENT,27000.00,Not Verified,debt_consolidation,Debt consolidation,NJ,18.67,0,0,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36 months,NaN,6.62,A,A2,Array Connector Corp,5,RENT,40000.00,Not Verified,home_improvement,LoanForGood_2012,FL,3.57,0,1,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,3148.0,40988.0,1

In [65]:
df.isnull().sum()

member_id                        0
loan_amnt                        0
funded_amnt                      0
funded_amnt_inv                  0
term                             0
batch_enrolled                   0
int_rate                         0
grade                            0
sub_grade                        0
emp_title                        0
emp_length                       0
home_ownership                   0
annual_inc                       0
verification_status              0
purpose                          0
title                            0
addr_state                       0
dti                              0
delinq_2yrs                      0
inq_last_6mths                   0
mths_since_last_delinq           0
open_acc                         0
pub_rec                          0
revol_bal                        0
revol_util                      29
total_acc                        0
initial_list_status              0
total_rec_int                    0
total_rec_late_fee               0
recoveries                       0
collection_recovery_fee          0
collections_12_mths_ex_med       8
application_type                 0
last_week_pay                    0
acc_now_delinq                   0
tot_coll_amt                  5124
tot_cur_bal                   5124
total_rev_hi_lim              5124
loan_status                      0
dtype: int64

# REPLACE MONTHS

In [39]:
df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36 months,,19.19,E,E3,clerk,9,OWN,28700.00,Source Verified,debt_consolidation,Debt consolidation,FL,33.88,0,1,50.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36 months,BAT1586599,10.99,B,B4,Human Resources Specialist,1,MORTGAGE,65000.00,Source Verified,home_improvement,Home improvement,MD,3.64,0,1,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36 months,BAT1586599,7.26,A,A4,Driver,2,OWN,45000.00,Not Verified,debt_consolidation,Debt consolidation,OH,18.42,0,0,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36 months,BAT4808022,19.72,D,D5,Us office of Personnel Management,10,RENT,105000.00,Not Verified,debt_consolidation,Debt consolidation,VA,14.97,0,2,46.0,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36 months,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10,RENT,52000.00,Verified,credit_card,refi,CA,20.16,0,0,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36 months,BAT2575549,8.90,A,A5,Design Consultant,2,MORTGAGE,120000.00,Not Verified,debt_consolidation,Credit Card Debt Consolidation,IN,12.30,0,0,56.0,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36 months,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5,RENT,75000.00,Source Verified,debt_consolidation,PAY THEM OFF,CA,5.70,0,0,NaN,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36 months,NaN,9.17,B,B1,Banker,8,MORTGAGE,54000.00,Not Verified,credit_card,Credit card refinancing,AL,11.63,0,1,46.0,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36 months,BAT4136152,13.99,C,C4,LVN,7,MORTGAGE,92000.00,Not Verified,home_improvement,Home improvement,CA,30.85,0,0,77.0,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60 months,BAT4694572,17.14,D,D4,Registered Nurse,2,MORTGAGE,72000.00,Verified,debt_consolidation,Debt consolidation,KY,33.92,0,0,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36 months,,13.33,C,C3,VP of Operations,10,OWN,135000.00,Source Verified,credit_card,Credit card refinancing,NM,14.20,0,1,52.0,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36 months,,18.49,D,D2,Jp Morgan chase bank,4,RENT,76000.00,Verified,debt_consolidation,Loan to payoff credit card debt,CA,15.86,0,1,82.0,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36 months,BAT5924421,6.99,A,A3,driver,7,MORTGAGE,62000.00,Not Verified,credit_card,Credit card refinancing,TN,18.58,0,2,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36 months,BAT3193689,6.03,A,A1,Federal Law Enforcement,10,MORTGAGE,145000.00,Not Verified,credit_card,Credit card refinancing,TX,15.42,0,0,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36 months,BAT224923,13.65,C,C1,Truck Driver,10,RENT,80000.00,Not Verified,debt_consolidation,Debt consolidation,CA,13.98,0,1,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36 months,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4,RENT,50000.00,Source Verified,debt_consolidation,Debt consolidation,CA,27.39,0,2,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60 months,BAT1930365,21.70,E,E2,LS1,9,RENT,69000.00,Source Verified,debt_consolidation,Debt Consolidation,CA,24.28,0,0,72.0,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36 months,,16.99,D,D1,NaN,nan,MORTGAGE,70000.00,Verified,credit_card,Credit card refinancing,PA,29.13,3,2,11.0,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36 months,BAT3873588,9.99,B,B3,Production employee,7,RENT,60000.00,Source Verified,debt_consolidation,Debt consolidation,KS,19.70,0,0,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36 months,NaN,10.99,B,B4,Principal Consultant,7,RENT,130000.00,Verified,debt_consolidation,Debt consolidation,IL,23.22,0,1,56.0,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60 months,BAT2252229,17.86,D,D5,Zone business manager,9,RENT,96000.00,Not Verified,debt_consolidation,Debt consolidation,FL,18.31,1,0,18.0,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36 months,BAT1135695,6.62,A,A2,Expeditors,2,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36 months,,17.57,D,D4,production coordinator,10,MORTGAGE,46000.00,Not Verified,debt_consolidation,Debt consolidation,CA,31.25,1,0,20.0,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36 months,BAT4694572,13.66,C,C3,Title Manager,7,OWN,60000.00,Source Verified,debt_consolidation,Debt consolidation,MO,13.82,0,1,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36 months,BAT4271519,7.89,A,A5,Coordinator,1,RENT,65000.00,Source Verified,debt_consolidation,Debt consolidation,FL,21.54,0,0,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60 months,,15.61,D,D1,Quality Engineer,4,MORTGAGE,70000.00,Source Verified,debt_consolidation,Debt consolidation,NC,21.93,0,0,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36 months,NaN,12.99,C,C1,Top shelf sales,2,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,TX,13.43,0,0,73.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36 months,NaN,6.62,A,A2,Physician,1,MORTGAGE,250000.00,Source Verified,debt_consolidation,Close cards and consolidate,AL,25.86,0,1,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36 months,BAT1184694,6.92,A,A4,Teacher,3,MORTGAGE,90000.00,Verified,debt_consolidation,Debt consolidation,TX,29.68,0,1,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36 months,BAT1586599,17.57,D,D4,cna,2,MORTGAGE,20000.00,Verified,other,Other,NJ,30.79,0,0,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60 months,BAT1104812,18.84,E,E2,Manager,5,RENT,114000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.56,0,2,68.0,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60 months,,17.77,D,D1,ECC,3,MORTGAGE,68000.00,Verified,debt_consolidation,Pool,MA,10.34,0,1,30.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36 months,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,1,MORTGAGE,100000.00,Not Verified,medical,Medical expenses,CA,3.31,0,0,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60 months,BAT4271519,17.57,D,D4,Vocational Counselor,10,RENT,43008.00,Not Verified,debt_consolidation,Debt consolidation,MO,19.50,0,0,NaN,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60 months,NaN,17.57,D,D4,Securities broker,8,MORTGAGE,250000.00,Source Verified,debt_consolidation,Debt consolidation,AR,13.18,2,1,3.0,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36 months,BAT2833642,13.05,B,B5,New York Life Insurance Company,3,RENT,74000.00,Verified,debt_consolidation,Debt consolidation,NY,18.40,0,0,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36 months,,12.12,B,B3,Comforce Telecom,10,MORTGAGE,63300.00,Verified,debt_consolidation,Credit Card Consolidation,FL,27.51,0,0,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36 months,,12.99,B,B5,Process Operator,7,MORTGAGE,80000.00,Source Verified,debt_consolidation,Debt consolidation,IN,9.44,0,0,57.0,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60 months,BAT2803411,15.41,D,D1,Vice President mortgage sales,2,MORTGAGE,75000.00,Source Verified,debt_consolidation,Debt consolidation,TN,24.21,2,2,12.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36 months,BAT3873588,9.17,B,B2,Nurse,8,MORTGAGE,88000.00,Not Verified,home_improvement,Home improvement,AR,17.52,0,1,36.0,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36 months,,13.35,C,C2,Nurse,10,RENT,60000.00,Not Verified,debt_consolidation,Debt consolidation,FL,24.68,0,0,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36 months,,15.61,D,D1,Patient account rep,8,MORTGAGE,43000.00,Verified,debt_consolidation,Debt consolidation,MN,20.76,1,1,NaN,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36 months,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4,MORTGAGE,109000.00,Not Verified,debt_consolidation,Debt consolidation,CT,10.28,0,0,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36 months,BAT2558388,12.39,C,C1,Research Scientist,4,RENT,71000.00,Not Verified,debt_consolidation,Debt consolidation,CA,16.41,0,0,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36 months,NaN,15.61,D,D1,NaN,nan,MORTGAGE,79384.56,Source Verified,debt_consolidation,Debt consolidation,SC,31.29,0,0,NaN,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36 months,BAT2575549,14.30,C,C1,Technical Support,1,RENT,35000.00,Verified,credit_card,Debt Consolidation,TX,15.22,0,2,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60 months,BAT1780517,13.33,C,C3,SUPERVISOR,1,RENT,55000.00,Source Verified,credit_card,Credit card refinancing,CA,12.46,0,0,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60 months,,23.99,F,F3,Assistant Project Director,6,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.78,0,1,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36 months,NaN,11.99,B,B3,NaN,9,RENT,65000.00,Verified,debt_consolidation,Bye bye Debt!,CA,7.09,0,0,79.0,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,INDIVIDUAL,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36 months,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36 months,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36 months,BAT5811547,8.90,A,A5,Creative Technology,10,MORTGAGE,160000.00,Source Verified,debt_consolidation,Get Rid Of Debt,OH,12.83,0,2,24.0,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36 months,NaN,18.55,D,D2,Senior Estimator,10,RENT,40000.00,Not Verified,debt_consolidation,The Great Payoff,MO,18.69,0,1,57.0,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36 months,BAT1184694,15.61,D,D1,Account executive,2,RENT,148000.00,Source Verified,debt_consolidation,Debt consolidation,CA,7.07,0,0,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36 months,,12.39,C,C1,Payroll and billing specialist,2,RENT,40000.00,Not Verified,debt_consolidation,Debt consolidation,IL,8.43,9,1,17.0,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36 months,BAT2252229,9.99,B,B3,Manager,1,RENT,60000.00,Source Verified,credit_card,Credit card refinancing,NJ,17.48,0,0,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36 months,BAT47674,8.90,A,A5,ATT Prime Communications,2,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36 months,NaN,6.24,A,A2,Account Executive,2,RENT,85000.00,Not Verified,major_purchase,Major purchase,CA,9.40,0,0,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,INDIVIDUAL,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36 months,,11.53,B,B5,Assistant instructor,3,RENT,27000.00,Not Verified,debt_consolidation,Debt consolidation,NJ,18.67,0,0,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36 months,NaN,6.62,A,A2,Array Connector Corp,5,RENT,40000.00,Not Verified,home_improvement,LoanForGood_2012,FL,3.57,0,1,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,3148.0,40988.0,1

In [40]:
li=[]
for j in df['term']:
    i = str(j)
    a = i.replace(' ','')
    b = a.replace('months','')
    li.append(b)
    #df['term'] = li

In [41]:
len(li)

63999

In [42]:
df['term'] = li

In [43]:
df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36,,19.19,E,E3,clerk,9,OWN,28700.00,Source Verified,debt_consolidation,Debt consolidation,FL,33.88,0,1,50.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36,BAT1586599,10.99,B,B4,Human Resources Specialist,1,MORTGAGE,65000.00,Source Verified,home_improvement,Home improvement,MD,3.64,0,1,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36,BAT1586599,7.26,A,A4,Driver,2,OWN,45000.00,Not Verified,debt_consolidation,Debt consolidation,OH,18.42,0,0,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9th week,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36,BAT4808022,19.72,D,D5,Us office of Personnel Management,10,RENT,105000.00,Not Verified,debt_consolidation,Debt consolidation,VA,14.97,0,2,46.0,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10,RENT,52000.00,Verified,credit_card,refi,CA,20.16,0,0,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36,BAT2575549,8.90,A,A5,Design Consultant,2,MORTGAGE,120000.00,Not Verified,debt_consolidation,Credit Card Debt Consolidation,IN,12.30,0,0,56.0,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5,RENT,75000.00,Source Verified,debt_consolidation,PAY THEM OFF,CA,5.70,0,0,NaN,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117th week,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36,NaN,9.17,B,B1,Banker,8,MORTGAGE,54000.00,Not Verified,credit_card,Credit card refinancing,AL,11.63,0,1,46.0,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36,BAT4136152,13.99,C,C4,LVN,7,MORTGAGE,92000.00,Not Verified,home_improvement,Home improvement,CA,30.85,0,0,77.0,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60,BAT4694572,17.14,D,D4,Registered Nurse,2,MORTGAGE,72000.00,Verified,debt_consolidation,Debt consolidation,KY,33.92,0,0,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36,,13.33,C,C3,VP of Operations,10,OWN,135000.00,Source Verified,credit_card,Credit card refinancing,NM,14.20,0,1,52.0,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36,,18.49,D,D2,Jp Morgan chase bank,4,RENT,76000.00,Verified,debt_consolidation,Loan to payoff credit card debt,CA,15.86,0,1,82.0,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,95th week,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36,BAT5924421,6.99,A,A3,driver,7,MORTGAGE,62000.00,Not Verified,credit_card,Credit card refinancing,TN,18.58,0,2,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48th week,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36,BAT3193689,6.03,A,A1,Federal Law Enforcement,10,MORTGAGE,145000.00,Not Verified,credit_card,Credit card refinancing,TX,15.42,0,0,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36,BAT224923,13.65,C,C1,Truck Driver,10,RENT,80000.00,Not Verified,debt_consolidation,Debt consolidation,CA,13.98,0,1,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,82th week,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4,RENT,50000.00,Source Verified,debt_consolidation,Debt consolidation,CA,27.39,0,2,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60,BAT1930365,21.70,E,E2,LS1,9,RENT,69000.00,Source Verified,debt_consolidation,Debt Consolidation,CA,24.28,0,0,72.0,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96th week,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36,,16.99,D,D1,NaN,nan,MORTGAGE,70000.00,Verified,credit_card,Credit card refinancing,PA,29.13,3,2,11.0,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36,BAT3873588,9.99,B,B3,Production employee,7,RENT,60000.00,Source Verified,debt_consolidation,Debt consolidation,KS,19.70,0,0,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36,NaN,10.99,B,B4,Principal Consultant,7,RENT,130000.00,Verified,debt_consolidation,Debt consolidation,IL,23.22,0,1,56.0,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60,BAT2252229,17.86,D,D5,Zone business manager,9,RENT,96000.00,Not Verified,debt_consolidation,Debt consolidation,FL,18.31,1,0,18.0,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36,BAT1135695,6.62,A,A2,Expeditors,2,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NAth week,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36,,17.57,D,D4,production coordinator,10,MORTGAGE,46000.00,Not Verified,debt_consolidation,Debt consolidation,CA,31.25,1,0,20.0,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36,BAT4694572,13.66,C,C3,Title Manager,7,OWN,60000.00,Source Verified,debt_consolidation,Debt consolidation,MO,13.82,0,1,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30th week,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36,BAT4271519,7.89,A,A5,Coordinator,1,RENT,65000.00,Source Verified,debt_consolidation,Debt consolidation,FL,21.54,0,0,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60,,15.61,D,D1,Quality Engineer,4,MORTGAGE,70000.00,Source Verified,debt_consolidation,Debt consolidation,NC,21.93,0,0,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36,NaN,12.99,C,C1,Top shelf sales,2,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,TX,13.43,0,0,73.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70th week,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36,NaN,6.62,A,A2,Physician,1,MORTGAGE,250000.00,Source Verified,debt_consolidation,Close cards and consolidate,AL,25.86,0,1,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104th week,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36,BAT1184694,6.92,A,A4,Teacher,3,MORTGAGE,90000.00,Verified,debt_consolidation,Debt consolidation,TX,29.68,0,1,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36,BAT1586599,17.57,D,D4,cna,2,MORTGAGE,20000.00,Verified,other,Other,NJ,30.79,0,0,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60,BAT1104812,18.84,E,E2,Manager,5,RENT,114000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.56,0,2,68.0,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39th week,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60,,17.77,D,D1,ECC,3,MORTGAGE,68000.00,Verified,debt_consolidation,Pool,MA,10.34,0,1,30.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,122th week,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,1,MORTGAGE,100000.00,Not Verified,medical,Medical expenses,CA,3.31,0,0,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60,BAT4271519,17.57,D,D4,Vocational Counselor,10,RENT,43008.00,Not Verified,debt_consolidation,Debt consolidation,MO,19.50,0,0,NaN,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60,NaN,17.57,D,D4,Securities broker,8,MORTGAGE,250000.00,Source Verified,debt_consolidation,Debt consolidation,AR,13.18,2,1,3.0,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83th week,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36,BAT2833642,13.05,B,B5,New York Life Insurance Company,3,RENT,74000.00,Verified,debt_consolidation,Debt consolidation,NY,18.40,0,0,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131th week,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36,,12.12,B,B3,Comforce Telecom,10,MORTGAGE,63300.00,Verified,debt_consolidation,Credit Card Consolidation,FL,27.51,0,0,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36,,12.99,B,B5,Process Operator,7,MORTGAGE,80000.00,Source Verified,debt_consolidation,Debt consolidation,IN,9.44,0,0,57.0,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44th week,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60,BAT2803411,15.41,D,D1,Vice President mortgage sales,2,MORTGAGE,75000.00,Source Verified,debt_consolidation,Debt consolidation,TN,24.21,2,2,12.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4th week,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36,BAT3873588,9.17,B,B2,Nurse,8,MORTGAGE,88000.00,Not Verified,home_improvement,Home improvement,AR,17.52,0,1,36.0,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36,,13.35,C,C2,Nurse,10,RENT,60000.00,Not Verified,debt_consolidation,Debt consolidation,FL,24.68,0,0,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36,,15.61,D,D1,Patient account rep,8,MORTGAGE,43000.00,Verified,debt_consolidation,Debt consolidation,MN,20.76,1,1,NaN,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4,MORTGAGE,109000.00,Not Verified,debt_consolidation,Debt consolidation,CT,10.28,0,0,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36,BAT2558388,12.39,C,C1,Research Scientist,4,RENT,71000.00,Not Verified,debt_consolidation,Debt consolidation,CA,16.41,0,0,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36,NaN,15.61,D,D1,NaN,nan,MORTGAGE,79384.56,Source Verified,debt_consolidation,Debt consolidation,SC,31.29,0,0,NaN,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74th week,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36,BAT2575549,14.30,C,C1,Technical Support,1,RENT,35000.00,Verified,credit_card,Debt Consolidation,TX,15.22,0,2,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113th week,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60,BAT1780517,13.33,C,C3,SUPERVISOR,1,RENT,55000.00,Source Verified,credit_card,Credit card refinancing,CA,12.46,0,0,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17th week,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60,,23.99,F,F3,Assistant Project Director,6,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.78,0,1,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31th week,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36,NaN,11.99,B,B3,NaN,9,RENT,65000.00,Verified,debt_consolidation,Bye bye Debt!,CA,7.09,0,0,79.0,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,INDIVIDUAL,109th week,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17th week,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157th week,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36,BAT5811547,8.90,A,A5,Creative Technology,10,MORTGAGE,160000.00,Source Verified,debt_consolidation,Get Rid Of Debt,OH,12.83,0,2,24.0,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135th week,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36,NaN,18.55,D,D2,Senior Estimator,10,RENT,40000.00,Not Verified,debt_consolidation,The Great Payoff,MO,18.69,0,1,57.0,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52th week,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36,BAT1184694,15.61,D,D1,Account executive,2,RENT,148000.00,Source Verified,debt_consolidation,Debt consolidation,CA,7.07,0,0,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35th week,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36,,12.39,C,C1,Payroll and billing specialist,2,RENT,40000.00,Not Verified,debt_consolidation,Debt consolidation,IL,8.43,9,1,17.0,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61th week,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36,BAT2252229,9.99,B,B3,Manager,1,RENT,60000.00,Source Verified,credit_card,Credit card refinancing,NJ,17.48,0,0,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13th week,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36,BAT47674,8.90,A,A5,ATT Prime Communications,2,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78th week,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36,NaN,6.24,A,A2,Account Executive,2,RENT,85000.00,Not Verified,major_purchase,Major purchase,CA,9.40,0,0,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,INDIVIDUAL,22th week,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36,,11.53,B,B5,Assistant instructor,3,RENT,27000.00,Not Verified,debt_consolidation,Debt consolidation,NJ,18.67,0,0,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26th week,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36,NaN,6.62,A,A2,Array Connector Corp,5,RENT,40000.00,Not Verified,home_improvement,LoanForGood_2012,FL,3.57,0,1,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161th week,0,0.0,3148.0,40988.0,1

# REPLACE WEEKS

In [44]:
li=[]
for j in df['last_week_pay']:
    i = str(j)
    a = i.replace(' ','')
    b = a.replace('thweek','')
    li.append(b)
df['last_week_pay'] = li

In [45]:
df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36,,19.19,E,E3,clerk,9,OWN,28700.00,Source Verified,debt_consolidation,Debt consolidation,FL,33.88,0,1,50.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,28699.0,30800.0,0
1,70011223,4800,4800,4800.0,36,BAT1586599,10.99,B,B4,Human Resources Specialist,1,MORTGAGE,65000.00,Source Verified,home_improvement,Home improvement,MD,3.64,0,1,NaN,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9,0,0.0,9974.0,32900.0,0
2,70255675,10000,10000,10000.0,36,BAT1586599,7.26,A,A4,Driver,2,OWN,45000.00,Not Verified,debt_consolidation,Debt consolidation,OH,18.42,0,0,NaN,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9,0,65.0,38295.0,34900.0,0
3,1893936,15000,15000,15000.0,36,BAT4808022,19.72,D,D5,Us office of Personnel Management,10,RENT,105000.00,Not Verified,debt_consolidation,Debt consolidation,VA,14.97,0,2,46.0,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135,0,0.0,55564.0,24700.0,0
4,7652106,16000,16000,16000.0,36,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10,RENT,52000.00,Verified,credit_card,refi,CA,20.16,0,0,NaN,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96,0,0.0,47159.0,47033.0,0
5,10247268,15000,15000,14950.0,36,BAT2575549,8.90,A,A5,Design Consultant,2,MORTGAGE,120000.00,Not Verified,debt_consolidation,Credit Card Debt Consolidation,IN,12.30,0,0,56.0,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113,0,0.0,350619.0,29500.0,0
6,8089625,5000,5000,4975.0,36,,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5,RENT,75000.00,Source Verified,debt_consolidation,PAY THEM OFF,CA,5.70,0,0,NaN,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117,0,1023.0,13272.0,55500.0,1
7,23043116,6000,6000,6000.0,36,NaN,9.17,B,B1,Banker,8,MORTGAGE,54000.00,Not Verified,credit_card,Credit card refinancing,AL,11.63,0,1,46.0,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,0.0,272579.0,11800.0,0
8,45900933,6000,6000,6000.0,36,BAT4136152,13.99,C,C4,LVN,7,MORTGAGE,92000.00,Not Verified,home_improvement,Home improvement,CA,30.85,0,0,77.0,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44,0,0.0,281521.0,62100.0,0
9,41272507,34550,34550,34550.0,60,BAT4694572,17.14,D,D4,Registered Nurse,2,MORTGAGE,72000.00,Verified,debt_consolidation,Debt consolidation,KY,33.92,0,0,NaN,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52,0,0.0,76034.0,33200.0,0
10,56621560,25000,25000,24975.0,36,,13.33,C,C3,VP of Operations,10,OWN,135000.00,Source Verified,credit_card,Credit card refinancing,NM,14.20,0,1,52.0,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,72193.0,47000.0,0
11,4221941,15000,15000,15000.0,36,,18.49,D,D2,Jp Morgan chase bank,4,RENT,76000.00,Verified,debt_consolidation,Loan to payoff credit card debt,CA,15.86,0,1,82.0,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,95,0,0.0,39152.0,19600.0,1
12,43387539,18000,18000,18000.0,36,BAT5924421,6.99,A,A3,driver,7,MORTGAGE,62000.00,Not Verified,credit_card,Credit card refinancing,TN,18.58,0,2,NaN,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48,0,0.0,194011.0,139900.0,0
13,23001903,9000,9000,9000.0,36,BAT3193689,6.03,A,A1,Federal Law Enforcement,10,MORTGAGE,145000.00,Not Verified,credit_card,Credit card refinancing,TX,15.42,0,0,NaN,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,0.0,165164.0,43000.0,0
14,13670372,8800,8800,8800.0,36,BAT224923,13.65,C,C1,Truck Driver,10,RENT,80000.00,Not Verified,debt_consolidation,Debt consolidation,CA,13.98,0,1,NaN,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,82,0,0.0,39634.0,41200.0,1
15,49874851,8000,8000,8000.0,36,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4,RENT,50000.00,Source Verified,debt_consolidation,Debt consolidation,CA,27.39,0,2,NaN,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35,0,0.0,48488.0,18500.0,0
16,9878144,18450,18450,18450.0,60,BAT1930365,21.70,E,E2,LS1,9,RENT,69000.00,Source Verified,debt_consolidation,Debt Consolidation,CA,24.28,0,0,72.0,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96,0,0.0,71191.0,15900.0,0
17,12866989,30750,30750,30700.0,36,,16.99,D,D1,NaN,nan,MORTGAGE,70000.00,Verified,credit_card,Credit card refinancing,PA,29.13,3,2,11.0,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104,0,0.0,221335.0,17400.0,0
18,58568833,9000,9000,9000.0,36,BAT3873588,9.99,B,B3,Production employee,7,RENT,60000.00,Source Verified,debt_consolidation,Debt consolidation,KS,19.70,0,0,NaN,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,34538.0,17000.0,0
19,62725253,24000,24000,24000.0,36,NaN,10.99,B,B4,Principal Consultant,7,RENT,130000.00,Verified,debt_consolidation,Debt consolidation,IL,23.22,0,1,56.0,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,125903.0,31000.0,0
20,66791957,20000,20000,20000.0,60,BAT2252229,17.86,D,D5,Zone business manager,9,RENT,96000.00,Not Verified,debt_consolidation,Debt consolidation,FL,18.31,1,0,18.0,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,0.0,66738.0,27200.0,0
21,1699807,12400,12400,12400.0,36,BAT1135695,6.62,A,A2,Expeditors,2,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NA,0,NaN,NaN,NaN,0
22,54486146,4200,4200,4200.0,36,,17.57,D,D4,production coordinator,10,MORTGAGE,46000.00,Not Verified,debt_consolidation,Debt consolidation,CA,31.25,1,0,20.0,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31,0,0.0,282808.0,25700.0,0
23,41408977,10500,10500,10500.0,36,BAT4694572,13.66,C,C3,Title Manager,7,OWN,60000.00,Source Verified,debt_consolidation,Debt consolidation,MO,13.82,0,1,NaN,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30,0,0.0,71697.0,14300.0,1
24,63047232,16000,16000,16000.0,36,BAT4271519,7.89,A,A5,Coordinator,1,RENT,65000.00,Source Verified,debt_consolidation,Debt consolidation,FL,21.54,0,0,NaN,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,147448.0,41400.0,0
25,22741274,23800,23800,23800.0,60,,15.61,D,D1,Quality Engineer,4,MORTGAGE,70000.00,Source Verified,debt_consolidation,Debt consolidation,NC,21.93,0,0,NaN,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,0.0,327930.0,43400.0,0
26,17563299,7200,7200,7150.0,36,NaN,12.99,C,C1,Top shelf sales,2,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,TX,13.43,0,0,73.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70,0,0.0,8589.0,19800.0,1
27,10317534,19200,19200,19175.0,36,NaN,6.62,A,A2,Physician,1,MORTGAGE,250000.00,Source Verified,debt_consolidation,Close cards and consolidate,AL,25.86,0,1,NaN,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104,0,0.0,447388.0,33100.0,1
28,50609137,15000,15000,15000.0,36,BAT1184694,6.92,A,A4,Teacher,3,MORTGAGE,90000.00,Verified,debt_consolidation,Debt consolidation,TX,29.68,0,1,NaN,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35,0,0.0,114298.0,49900.0,0
29,70008968,4000,4000,4000.0,36,BAT1586599,17.57,D,D4,cna,2,MORTGAGE,20000.00,Verified,other,Other,NJ,30.79,0,0,NaN,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4,0,0.0,31445.0,10900.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60,BAT1104812,18.84,E,E2,Manager,5,RENT,114000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.56,0,2,68.0,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39,0,0.0,157141.0,47200.0,0
63970,6039679,21725,21725,21725.0,60,,17.77,D,D1,ECC,3,MORTGAGE,68000.00,Verified,debt_consolidation,Pool,MA,10.34,0,1,30.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,122,0,56.0,296940.0,7600.0,1
63971,65437502,2500,2500,2500.0,36,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,1,MORTGAGE,100000.00,Not Verified,medical,Medical expenses,CA,3.31,0,0,NaN,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,1428.0,294013.0,67100.0,0
63972,63622981,17200,17200,17200.0,60,BAT4271519,17.57,D,D4,Vocational Counselor,10,RENT,43008.00,Not Verified,debt_consolidation,Debt consolidation,MO,19.50,0,0,NaN,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,150815.0,29300.0,0
63973,19868235,35000,35000,35000.0,60,NaN,17.57,D,D4,Securities broker,8,MORTGAGE,250000.00,Source Verified,debt_consolidation,Debt consolidation,AR,13.18,2,1,3.0,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83,0,0.0,632686.0,32400.0,0
63974,7647338,24000,24000,24000.0,36,BAT2833642,13.05,B,B5,New York Life Insurance Company,3,RENT,74000.00,Verified,debt_consolidation,Debt consolidation,NY,18.40,0,0,NaN,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131,0,0.0,43946.0,46702.0,0
63975,1890604,15000,15000,15000.0,36,,12.12,B,B3,Comforce Telecom,10,MORTGAGE,63300.00,Verified,debt_consolidation,Credit Card Consolidation,FL,27.51,0,0,NaN,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,0.0,231063.0,24400.0,1
63976,16460359,18000,18000,18000.0,36,,12.99,B,B5,Process Operator,7,MORTGAGE,80000.00,Source Verified,debt_consolidation,Debt consolidation,IN,9.44,0,0,57.0,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44,0,0.0,57125.0,9000.0,0
63977,70619458,21200,21200,21200.0,60,BAT2803411,15.41,D,D1,Vice President mortgage sales,2,MORTGAGE,75000.00,Source Verified,debt_consolidation,Debt consolidation,TN,24.21,2,2,12.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4,0,0.0,88497.0,11700.0,0
63978,58837067,9000,9000,9000.0,36,BAT3873588,9.17,B,B2,Nurse,8,MORTGAGE,88000.00,Not Verified,home_improvement,Home improvement,AR,17.52,0,1,36.0,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,194.0,223720.0,20100.0,0
63979,35643212,6000,6000,6000.0,36,,13.35,C,C2,Nurse,10,RENT,60000.00,Not Verified,debt_consolidation,Debt consolidation,FL,24.68,0,0,NaN,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,0.0,40418.0,23900.0,0
63980,55478345,3000,3000,3000.0,36,,15.61,D,D1,Patient account rep,8,MORTGAGE,43000.00,Verified,debt_consolidation,Debt consolidation,MN,20.76,1,1,NaN,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,26144.0,8100.0,0
63981,54007397,12800,12800,12800.0,36,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4,MORTGAGE,109000.00,Not Verified,debt_consolidation,Debt consolidation,CT,10.28,0,0,NaN,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,INDIVIDUAL,31,0,0.0,30253.0,47600.0,0
63982,37016622,15000,15000,15000.0,36,BAT2558388,12.39,C,C1,Research Scientist,4,RENT,71000.00,Not Verified,debt_consolidation,Debt consolidation,CA,16.41,0,0,NaN,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,0.0,28156.0,20500.0,0
63983,26507802,34875,34875,34625.0,36,NaN,15.61,D,D1,NaN,nan,MORTGAGE,79384.56,Source Verified,debt_consolidation,Debt consolidation,SC,31.29,0,0,NaN,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74,0,1849.0,229007.0,40300.0,0
63984,1478303,7500,7500,7500.0,36,BAT2575549,14.30,C,C1,Technical Support,1,RENT,35000.00,Verified,credit_card,Debt Consolidation,TX,15.22,0,2,NaN,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113,0,0.0,19572.0,39300.0,0
63985,62374014,27500,27500,27500.0,60,BAT1780517,13.33,C,C3,SUPERVISOR,1,RENT,55000.00,Source Verified,credit_card,Credit card refinancing,CA,12.46,0,0,NaN,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,26926.0,48100.0,0
63986,55289340,12050,12050,12050.0,60,,23.99,F,F3,Assistant Project Director,6,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.78,0,1,NaN,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31,0,0.0,36695.0,16500.0,0
63987,9177047,5600,5600,5600.0,36,NaN,11.99,B,B3,NaN,9,RENT,65000.00,Verified,debt_consolidation,Bye bye Debt!,CA,7.09,0,0,79.0,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,INDIVIDUAL,109,0,0.0,7891.0,6900.0,0
63988,980233,2000,2000,1975.0,36,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17,0,NaN,NaN,NaN,0
63989,823165,20000,20000,19950.0,36,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,NaN,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
63990,2728636,18000,18000,18000.0,36,BAT5811547,8.90,A,A5,Creative Technology,10,MORTGAGE,160000.00,Source Verified,debt_consolidation,Get Rid Of Debt,OH,12.83,0,2,24.0,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135,0,0.0,271843.0,42000.0,1
63991,9397061,10000,10000,10000.0,36,NaN,18.55,D,D2,Senior Estimator,10,RENT,40000.00,Not Verified,debt_consolidation,The Great Payoff,MO,18.69,0,1,57.0,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52,0,94.0,21772.0,12800.0,1
63992,51613614,28000,28000,28000.0,36,BAT1184694,15.61,D,D1,Account executive,2,RENT,148000.00,Source Verified,debt_consolidation,Debt consolidation,CA,7.07,0,0,NaN,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35,0,0.0,35430.0,31700.0,0
63993,37016497,1750,1750,1750.0,36,,12.39,C,C1,Payroll and billing specialist,2,RENT,40000.00,Not Verified,debt_consolidation,Debt consolidation,IL,8.43,9,1,17.0,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,0.0,31906.0,2900.0,0
63994,66009021,15000,15000,15000.0,36,BAT2252229,9.99,B,B3,Manager,1,RENT,60000.00,Source Verified,credit_card,Credit card refinancing,NJ,17.48,0,0,NaN,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,0.0,28561.0,39700.0,0
63995,1363172,6000,6000,6000.0,36,BAT47674,8.90,A,A5,ATT Prime Communications,2,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,NaN,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,NaN,NaN,NaN,1
63996,60869253,4200,4200,4200.0,36,NaN,6.24,A,A2,Account Executive,2,RENT,85000.00,Not Verified,major_purchase,Major purchase,CA,9.40,0,0,NaN,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,INDIVIDUAL,22,0,0.0,34544.0,51200.0,0
63997,55298262,10000,10000,10000.0,36,,11.53,B,B5,Assistant instructor,3,RENT,27000.00,Not Verified,debt_consolidation,Debt consolidation,NJ,18.67,0,0,NaN,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,21061.0,23500.0,0
63998,2430978,12300,12300,12300.0,36,NaN,6.62,A,A2,Array Connector Corp,5,RENT,40000.00,Not Verified,home_improvement,LoanForGood_2012,FL,3.57,0,1,NaN,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,0.0,3148.0,40988.0,1

# To FIll NULL VALUES

In [46]:
df['emp_length'].unique()

array(['9', '1', '2', 10, '5', '8', '7', '4', 'nan', '3', '6', 20, 15, 30],
      dtype=object)

In [47]:
df['emp_length'].value_counts()

10     20925
1       9175
2       5697
3       4979
5       4021
4       3760
nan     3324
7       3286
8       3179
6       3121
9       2490
15        36
20         5
30         1
Name: emp_length, dtype: int64

In [48]:
df['emp_length'].replace('nan',df['emp_length'].median(),inplace=True)

In [49]:
df['emp_length'].replace(df['emp_length'].median(),6,inplace=True)

In [86]:
df.isnull().sum()

member_id                        0
loan_amnt                        0
funded_amnt                      0
funded_amnt_inv                  0
term                             0
batch_enrolled                   0
int_rate                         0
grade                            0
sub_grade                        0
emp_title                        0
emp_length                       0
home_ownership                   0
annual_inc                       0
verification_status              0
purpose                          0
title                            0
addr_state                       0
dti                              0
delinq_2yrs                      0
inq_last_6mths                   0
mths_since_last_delinq           0
open_acc                         0
pub_rec                          0
revol_bal                        0
revol_util                       0
total_acc                        0
initial_list_status              0
total_rec_int                    0
total_rec_late_fee               0
recoveries                       0
collection_recovery_fee          0
collections_12_mths_ex_med       0
application_type                 0
last_week_pay                    0
acc_now_delinq                   0
tot_coll_amt                  5124
tot_cur_bal                   5124
total_rev_hi_lim                 0
loan_status                      0
dtype: int64

In [52]:
# batch_enrolled
df['batch_enrolled'].fillna(method='ffill',inplace=True)

In [53]:
df['batch_enrolled'].value_counts()

              15091
BAT2252229     2677
BAT3873588     2435
BAT2803411     2405
BAT1780517     2062
BAT2078974     2048
BAT1586599     2046
BAT4694572     1951
BAT1104812     1860
BAT1184694     1679
BAT3726927     1625
BAT4271519     1563
BAT3193689     1504
BAT4136152     1387
BAT2558388     1376
BAT5924421     1305
BAT2136391     1109
BAT5489674     1059
BAT2333412     1050
BAT3461431      993
BAT2522922      897
BAT1766061      896
BAT5629144      862
BAT2575549      852
BAT224923       847
BAT5525466      732
BAT1930365      730
BAT4351734      709
BAT2833642      688
BAT2003848      657
              ...
BAT3157685       43
BAT3594334       38
BAT3518025       32
BAT3839056       31
BAT1864701       29
BAT4260473       28
BAT4201183       26
BAT4734809       25
BAT3975721       24
BAT3275209       21
BAT4935307       20
BAT348786        19
BAT1575727       17
BAT291187        14
BAT5477261       13
BAT4726815       13
BAT3706046       13
BAT4160421       13
BAT578944        12
BAT447257        12
BAT3537993       10
BAT4939736        8
BAT3147293        7
BAT3965509        6
BAT3474907        6
BAT4884699        5
BAT2143459        4
BAT4250975        3
BAT5869156        2
BAT4347689        2
Name: batch_enrolled, Length: 102, dtype: int64

In [54]:
df['batch_enrolled'].replace(' ','OTHERS',inplace=True)

In [55]:
# emp_title
df['emp_title'].fillna('N.A',inplace=True)

In [56]:
# title
fg=[]
for i in df['title']:
    fg.append(str(i))
df['title'] = fg

In [57]:
df[df['title'] == 'nan']

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
37,72929339,10000,10000,10000.0,60,BAT2803411,14.85,C,C5,EMR Content Specialist,10,MORTGAGE,45000.0,Not Verified,debt_consolidation,nan,IN,26.76,0,0,25.0,14,0,17916,48.3,28,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,176391.0,37100.0,0
6734,73190585,8000,8000,8000.0,36,BAT2803411,13.99,C,C4,N.A,6,MORTGAGE,50000.0,Not Verified,debt_consolidation,nan,MD,19.85,0,0,60.0,8,0,29588,83.3,18,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,294264.0,162000.0,0
9483,72927442,8000,8000,8000.0,36,BAT2803411,6.49,A,A2,Director,2,MORTGAGE,112000.0,Not Verified,credit_card,nan,IL,14.52,0,2,53.0,19,0,7002,10.3,46,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,278532.0,67900.0,0
18786,72927876,2200,2200,2200.0,36,BAT2803411,13.99,C,C4,N.A,6,MORTGAGE,48000.0,Source Verified,home_improvement,nan,MN,6.81,0,1,66.0,15,1,3934,31.7,26,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,5245.0,12400.0,0
22899,72927235,20000,20000,20000.0,36,OTHERS,14.85,C,C5,Accountant,10,RENT,91255.0,Verified,medical,nan,KS,13.20,1,1,16.0,4,0,10962,87.7,27,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,33780.0,12500.0,0
26270,72927507,35000,35000,35000.0,36,BAT4351734,10.78,B,B4,Supervision and Risk Coordinator,10,MORTGAGE,134000.0,Verified,debt_consolidation,nan,TX,23.09,0,1,NaN,10,0,37482,88.6,15,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,521944.0,42300.0,0
29528,689802,6000,6000,5950.0,36,BAT5540558,11.49,B,B4,N.A,7,MORTGAGE,96000.0,Not Verified,small_business,nan,CO,9.06,1,2,23.0,16,0,4217,16.3,27,f,1118.44,0.0,0.0,0.0,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
33010,72929482,3500,3500,3500.0,36,BAT2803411,12.88,C,C2,cosmetologist,8,RENT,83200.0,Not Verified,other,nan,FL,1.30,4,2,23.0,7,0,1481,15.6,15,w,0.00,0.0,0.0,0.0,1.0,INDIVIDUAL,NA,0,780.0,3144.0,9500.0,0
35093,72928889,4800,4800,4800.0,36,BAT2803411,14.85,C,C5,Quality Control Technician,1,RENT,19500.0,Source Verified,debt_consolidation,nan,GA,5.23,0,0,29.0,6,0,1810,8.8,13,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,1810.0,20600.0,0
42850,1785959,16000,16000,16000.0,60,BAT1586599,21.00,E,E2,Zirmed Inc,4,MORTGAGE,61000.0,Verified,debt_consolidation,nan,KY,7.24,0,1,48.0,8,0,7890,72.2,26,f,8590.05,0.0,0.0,0.0,0.0,INDIVIDUAL,174,0,0.0,138630.0,10928.0,0
47085,689914,1800,1800,1800.0,36,OTHERS,14.84,D,D1,Fresh Produce Sportswear,6,OWN,30000.0,Not Verified,debt_consolidation,nan,CA,7.72,0,0,NaN,4,0,1571,94.5,8,f,439.90,0.0,0.0,0.0,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
52346,72928789,20000,20000,20000.0,60,BAT2803411,10.78,B,B4,truck driver,10,MORTGAGE,63000.0,Not Verified,home_improvement,nan,IL,10.78,0,0,NaN,6,0,7869,56.2,18,w,0.00,0.0,0.0,0.0,0.0,JOINT,NA,0,0.0,189699.0,14000.0,0
52542,72621916,7500,7500,7500.0,36,BAT1184694,11.99,C,C1,design consultant,2,RENT,111000.0,Source Verified,debt_consolidation,nan,CA,14.09,0,1,25.0,9,0,14995,73.9,14,w,0.00,0.0,0.0,0.0,0.0,INDIVIDUAL,NA,0,0.0,34363.0,20300.0,0

In [58]:
a = df['member_id'][df['title'] == 'nan']


a

37       72929339
6734     73190585
9483     72927442
18786    72927876
22899    72927235
26270    72927507
29528      689802
33010    72929482
35093    72928889
42850     1785959
47085      689914
52346    72928789
52542    72621916
Name: member_id, dtype: int64

In [59]:
for i in a:
    df['title'][df['member_id']==i] = df['purpose'][df['member_id']==i]

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [60]:
# mths_since_last_delinq

In [61]:
df['mths_since_last_delinq'].median()

30.0

In [62]:
li=[]
for i in df['mths_since_last_delinq']:
    j = str(i)
    li.append(j)

In [63]:
df['mths_since_last_delinq'] = li

In [64]:

mask= ((df['mths_since_last_delinq']== 'nan') & (df['delinq_2yrs']==0))
df['mths_since_last_delinq'][mask] = 30

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [66]:
# revol_util
ch=[]
for i in df['revol_util']:
    j = str(i)
    ch.append(j)

In [67]:
df['revol_util'] = ch

In [68]:
mask = ((df['revol_bal'] == 0) & (df['revol_util'] == 'nan'))
df['revol_util'][mask] = 0

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [69]:
df[df['revol_util'] == 'nan']

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
16180,58639359,12000,12000,12000.0,36,BAT3873588,13.33,C,C3,foreman,10,MORTGAGE,60000.0,Source Verified,debt_consolidation,Debt consolidation,PA,20.10,0,1,30,5,0,46139,nan,16,f,639.78,0.0,0.0,0.0,0.0,INDIVIDUAL,22,0,0.0,77661.0,46000.0,0
22047,17704000,35000,35000,35000.0,36,OTHERS,16.29,D,D2,trader,10,MORTGAGE,275000.0,Verified,other,Other,TN,11.13,0,0,30,5,0,35314,nan,19,w,7118.79,0.0,0.0,0.0,0.0,INDIVIDUAL,83,0,17478.0,386060.0,34000.0,0
22585,18343742,15000,15000,15000.0,36,BAT2136391,6.03,A,A1,Senior Product Manager,1,MORTGAGE,130000.0,Verified,debt_consolidation,Debt consolidation,MD,22.07,0,0,30,9,0,88157,nan,28,f,840.99,0.0,0.0,0.0,0.0,INDIVIDUAL,57,0,0.0,467630.0,116000.0,1
44730,29193037,12500,12500,12500.0,60,BAT2003848,13.35,C,C2,Software Engineer,10,MORTGAGE,139000.0,Source Verified,home_improvement,Home improvement,MD,16.38,2,0,11.0,6,0,146843,nan,26,f,1971.30,0.0,0.0,0.0,0.0,INDIVIDUAL,70,0,390.0,789224.0,150000.0,0
53337,63078310,35000,35000,35000.0,36,BAT4271519,14.65,C,C5,"VP, Global Leverage",10,MORTGAGE,300000.0,Source Verified,debt_consolidation,Debt consolidation,AR,11.36,0,0,30,5,0,33907,nan,13,f,1596.52,0.0,0.0,0.0,0.0,INDIVIDUAL,13,0,0.0,779978.0,35000.0,1
58715,30995879,20000,20000,20000.0,60,BAT2078974,15.61,D,D1,Associate General Counsel,3,MORTGAGE,102400.0,Source Verified,other,Other,NY,36.25,1,0,7.0,8,1,52331,nan,47,w,3581.41,0.0,0.0,0.0,0.0,INDIVIDUAL,65,0,0.0,148225.0,55000.0,0

In [70]:
dc = df['member_id'][df['revol_util']=='nan']

In [71]:
dc

16180    58639359
22047    17704000
22585    18343742
44730    29193037
53337    63078310
58715    30995879
Name: member_id, dtype: int64

In [72]:
for i in dc:
    df['revol_util'][df['member_id']==i] = (df['revol_bal'][df['member_id']==i]/df['total_rev_hi_lim'][df['member_id']==i])*100

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [73]:
df['revol_util'].value_counts()

0.0                  239
50.0                 132
46.0                 132
75.0                 129
62.0                 129
64.0                 127
55.0                 127
56.0                 127
60.0                 126
49.0                 126
63.0                 125
68.0                 125
53.0                 124
58.0                 123
44.0                 122
54.0                 122
52.0                 122
48.0                 121
40.0                 119
59.0                 119
39.0                 117
54.2                 117
65.0                 116
49.9                 116
70.0                 115
47.0                 114
61.2                 113
78.0                 112
69.0                 112
61.0                 112
                    ...
107.4                  1
103.1                  1
105.3                  1
106.4                  1
103.0                  1
97.89533333333334      1
108.1                  1
104.1                  1
0.12                   1
108.6                  1
103.6                  1
115.3                  1
4.85                   1
118.4                  1
105.9                  1
113.4                  1
120.5                  1
141.1                  1
126.4                  1
104.5                  1
106.2                  1
112.0                  1
111.4                  1
104.9                  1
128.4                  1
33.14                  1
7.28                   1
23.11                  1
101.7                  1
130.8                  1
Name: revol_util, Length: 1097, dtype: int64

In [77]:
#collections_12_mths_ex_med
df['collections_12_mths_ex_med'].fillna(0.0,inplace=True)

In [129]:
# tot_coll_amt
df[df['tot_coll_amt'].isnull()==True]

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
21,1699807,12400,12400,12400.000000,36,BAT1135695,6.62,A,A2,Expeditors,2,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NA,0,NaN,NaN,14786.885246,0
47,1561871,20000,20000,19725.000000,36,OTHERS,13.67,B,B5,Credit Suisse,4,RENT,168000.00,Verified,debt_consolidation,Grateful Getting Out of Debt For Good,NY,22.32,0,0,41.0,5,0,24080,80.0,19,f,4255.21,68.040000,750.11,134.7958,0.0,INDIVIDUAL,135,0,NaN,NaN,30100.000000,0
66,1665246,16000,16000,15975.000000,36,OTHERS,6.03,A,A1,Merrill Lynch,4,MORTGAGE,75000.00,Verified,small_business,Business funding,TX,4.83,0,0,30,6,0,1079,2.9,8,f,1438.43,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117,0,NaN,NaN,37206.896552,1
67,1604702,35000,35000,34975.000000,36,BAT3943761,19.72,D,D5,N.A,10,MORTGAGE,140000.00,Verified,small_business,Business,PA,30.35,0,1,36.0,16,0,88474,80.1,47,f,11640.25,0.000000,0.00,0.0000,0.0,INDIVIDUAL,156,0,NaN,NaN,110454.431960,1
74,1605934,1000,1000,1000.000000,36,BAT3943761,12.12,B,B3,NFI Industries,8,RENT,40000.00,Verified,vacation,Vacation,OH,31.77,0,0,30,12,0,15686,93.4,21,f,197.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,156,0,NaN,NaN,16794.432548,1
93,690194,8000,8000,7950.000000,36,BAT5540558,10.38,B,B1,Boston and North Shore Real Estate,2,RENT,50004.00,Verified,other,Business Idea Head Start,MA,23.88,0,2,30,8,0,13964,57.5,22,f,330.23,29.950575,318.09,3.2000,0.0,INDIVIDUAL,26,0,NaN,NaN,24285.217391,0
123,1379776,5700,5700,5700.000000,60,BAT47674,19.42,E,E3,Sunharbor Manor Skilled Nursing,3,RENT,50000.00,Verified,debt_consolidation,Debt Consolidation Loan,NY,8.90,0,0,43.0,12,0,8009,69.0,29,f,2576.60,0.000000,0.00,0.0000,0.0,INDIVIDUAL,152,0,NaN,NaN,11607.246377,1
130,1406917,10000,10000,9750.000000,36,BAT1327206,13.11,B,B4,Mountain Side Trans,10,RENT,72000.00,Source Verified,debt_consolidation,debt consoldidation,NY,5.17,0,0,30,9,0,11220,58.7,19,f,2150.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,156,0,NaN,NaN,19114.139693,1
150,532287,18000,18000,17045.561357,36,BAT4201183,18.78,F,F3,Astir IT Solutions Inc,3,RENT,80000.00,Not Verified,wedding,personal,VA,15.60,0,0,30,4,0,11184,93.2,8,f,5769.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,12000.000000,1
152,1355282,15000,15000,15000.000000,36,BAT47674,13.49,C,C1,"Yahoo!, Inc.",4,RENT,75000.00,Verified,debt_consolidation,Cutting the Card,CA,8.75,0,0,30,7,0,13305,88.7,14,f,2886.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104,0,NaN,NaN,15000.000000,1
193,1607923,9000,9000,8975.000000,36,BAT3943761,15.31,C,C3,SuperValu,1,OWN,40000.00,Verified,debt_consolidation,Debt Consolidation,IL,23.52,0,1,30,15,0,7290,57.4,25,f,2308.54,0.000000,0.00,0.0000,0.0,INDIVIDUAL,170,0,NaN,NaN,12700.348432,1
195,1505478,16800,16800,16800.000000,60,BAT2677031,12.12,B,B3,State Farm Insurance,5,RENT,38000.00,Verified,debt_consolidation,4mygood,NC,14.78,0,0,30,8,0,20295,64.8,12,f,4093.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131,0,NaN,NaN,31319.444444,1
197,1572896,18000,18000,17975.000000,36,BAT3292317,7.90,A,A4,INTERNOTES STRATEGY CO,10,OWN,150000.00,Source Verified,debt_consolidation,debt_consolidation,NY,7.86,0,1,81.0,17,1,4593,13.2,43,f,1308.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,NaN,NaN,34795.454545,1
207,1109629,2400,2400,2400.000000,36,BAT1914408,12.69,B,B5,MIQ Logisitics LLC,5,MORTGAGE,92000.00,Not Verified,home_improvement,Home Improvement,MO,20.40,0,1,30,11,0,23347,88.1,39,f,495.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,26500.567537,1
208,416096,7000,7000,6754.960000,36,BAT1914408,16.32,E,E3,Dutch Productions Inc.,3,RENT,55000.00,Source Verified,debt_consolidation,Mwood Ploan,NY,3.99,1,1,22.0,5,0,4747,93.1,10,f,1651.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104,0,NaN,NaN,5098.818475,1
219,1240323,35000,35000,35000.000000,36,BAT1942645,10.65,B,B2,H WEISS,7,MORTGAGE,90000.00,Verified,debt_consolidation,debt consolidation loan,NY,17.41,0,1,30,12,0,42673,41.3,42,f,6033.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,152,0,NaN,NaN,103324.455206,1
238,842080,25000,25000,24975.000000,36,BAT5458862,13.80,C,C4,N.A,6,MORTGAGE,96000.00,Source Verified,small_business,Small Business Loan,VA,1.48,0,3,38.0,7,0,6357,25.0,21,f,5667.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,25428.000000,1
244,1208136,3000,3000,3000.000000,36,BAT2015867,11.71,B,B3,Aria Resort and Casino,1,MORTGAGE,45000.00,Not Verified,home_improvement,Landscaping,NV,15.23,0,0,30,5,0,863,86.3,8,f,569.92,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,1000.000000,1
251,1599768,21625,21625,21625.000000,60,BAT3943761,20.50,E,E2,U. S. Coast Guard,10,RENT,45000.00,Verified,debt_consolidation,New Debt,VA,32.51,0,0,45.0,7,0,17468,93.9,20,f,9392.55,14.950211,2279.63,22.6235,0.0,INDIVIDUAL,126,0,NaN,NaN,18602.768903,0
283,1225115,20000,20000,19700.000000,60,BAT1184694,12.69,B,B5,T. Rowe Price,4,RENT,55000.00,Verified,debt_consolidation,Credit Card Paydown,MD,29.26,0,0,30,7,0,18865,66.4,21,f,5565.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,148,0,NaN,NaN,28411.144578,1
296,946620,5500,5500,5425.000000,36,BAT1691418,5.42,A,A1,"M J MILLER, INC",2,OWN,35000.00,Not Verified,home_improvement,SPLASH,TX,7.71,0,0,30,7,0,5975,21.5,12,f,470.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,27790.697674,1
298,771068,4500,4500,4497.491474,60,OTHERS,6.17,A,A3,N.A,5,RENT,55000.00,Verified,credit_card,Help pay off the last credit card,HI,14.81,0,0,30,9,0,2645,13.8,18,f,741.16,0.000000,0.00,0.0000,0.0,INDIVIDUAL,265,0,NaN,NaN,19166.666667,1
303,1027808,18000,18000,18000.000000,36,BAT5877328,15.23,C,C5,SAIC,10,MORTGAGE,93000.00,Source Verified,home_improvement,Home Improvement Loan,VA,15.47,0,1,65.0,11,0,31800,66.0,28,f,4725.30,15.000000,0.00,0.0000,0.0,INDIVIDUAL,165,0,NaN,NaN,48181.818182,1
315,1701796,12000,12000,12000.000000,36,BAT1135695,6.62,A,A2,HUD,10,MORTGAGE,115000.00,Not Verified,debt_consolidation,Personal Loan,MD,3.30,0,1,30,9,0,23818,61.5,20,f,66.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4,0,NaN,NaN,38728.455285,1
335,1002373,1000,1000,1000.000000,36,OTHERS,18.39,E,E2,estes express lines,3,MORTGAGE,50300.00,Not Verified,vacation,Florida June 2011,AL,11.12,0,1,30,7,1,9959,95.8,10,f,306.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,10395.615866,1
336,744722,5000,5000,5000.000000,60,BAT5614983,10.75,B,B2,"Knapp I.T., Inc.",3,MORTGAGE,65000.00,Verified,home_improvement,Basement and insulation,DE,20.68,0,2,30,7,0,11490,41.2,15,f,1484.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,261,0,NaN,NaN,27888.349515,1
361,774488,7500,7500,7500.000000,60,BAT1755192,15.57,D,D5,CVS Pharmacy,3,MORTGAGE,69000.00,Source Verified,home_improvement,Home Improvement,NJ,3.86,0,5,61.0,6,0,7177,80.6,7,f,193.07,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,NaN,NaN,8904.466501,0
364,620684,8500,8500,8400.000000,36,BAT4786748,7.88,A,A5,Cross Country Staffing,2,RENT,47500.00,Not Verified,debt_consolidation,Credit,FL,11.70,0,0,30,9,0,9205,52.0,22,f,721.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74,0,NaN,NaN,17701.923077,1
371,1087011,9000,9000,9000.000000,60,BAT1914408,9.99,B,B1,Hensel Phelps Construction Company,10,MORTGAGE,146760.00,Verified,car,Auto,TX,29.79,0,0,30,9,0,35346,76.7,35,f,2378.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,213,0,NaN,NaN,46083.441982,1
383,1051047,5000,5000,4500.000000,60,OTHERS,7.49,A,A4,UPS,10,MORTGAGE,72600.00,Not Verified,car,Third Vehicle Loan,KY,13.59,0,0,30,9,0,4084,9.7,23,f,987.15,0.000000,0.00,0.0000,0.0,INDIVIDUAL,222,0,NaN,NaN,42103.092784,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63608,485332,8100,8100,7864.333224,36,OTHERS,7.14,A,A3,Blue Water Benefits,2,MORTGAGE,40000.00,Not Verified,debt_consolidation,Personal Loan,SC,6.96,0,0,30,8,0,5517,17.5,23,f,920.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,315.257143,1
63633,1633412,6500,6500,6500.000000,36,BAT3943761,17.77,D,D1,Sam's Club,5,RENT,30000.00,Verified,debt_consolidation,Credit Loan,NJ,14.44,0,1,30,11,0,13299,20.9,20,f,1912.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,143,0,NaN,NaN,636.315789,1
63663,409737,25000,25000,16691.495427,36,BAT4260473,14.11,D,D1,N.A,4,RENT,260735.00,Verified,small_business,Business Expansion / Working Capital,TX,7.82,0,0,45.0,12,0,11697,33.2,30,f,5798.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,352.319277,1
63664,1697264,3600,3600,3600.000000,36,BAT1135695,14.09,B,B5,N.A,6,MORTGAGE,25000.00,Not Verified,debt_consolidation,Help pay off high interest loan,DE,12.58,0,3,34.0,11,0,8112,50.8,32,f,580.16,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74,0,NaN,NaN,159.685039,1
63673,544427,18000,18000,17825.000000,36,BAT3518025,11.83,B,B3,Lindmore Irrigation District,2,MORTGAGE,128000.00,Source Verified,credit_card,9.09 Loan,CA,12.92,0,4,30,10,0,12204,64.6,39,f,2723.63,0.000000,0.00,0.0000,0.0,INDIVIDUAL,91,0,NaN,NaN,188.916409,1
63704,891873,15000,15000,14975.000000,36,BAT5320519,16.40,E,E1,crosby trucking,1,RENT,36000.00,Verified,small_business,Small Business Loan,NC,3.57,0,8,30,4,0,3160,62.0,5,f,4093.99,41.422153,0.00,0.0000,0.0,INDIVIDUAL,165,0,NaN,NaN,50.967742,1
63736,674813,25000,15425,13523.586385,60,BAT5540558,13.61,C,C2,Flex-n-gate,2,RENT,60000.00,Verified,credit_card,Debt consolidation loan,AL,22.34,0,0,30,5,0,22951,42.5,36,f,5235.03,0.000000,855.66,8.5566,0.0,INDIVIDUAL,183,0,NaN,NaN,540.023529,0
63744,386125,14000,14000,3150.000000,36,BAT1586599,11.89,B,B4,ARCADIS,4,MORTGAGE,84240.00,Verified,car,"Can I borrow some money, please?",CA,10.33,0,3,30,5,0,23149,32.6,15,f,909.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35,0,NaN,NaN,710.092025,1
63757,967013,15000,15000,14975.000000,36,BAT4051248,11.49,B,B4,DESE Research,1,MORTGAGE,95000.00,Verified,small_business,Small Business Capital,AL,16.16,0,0,30,8,0,55609,93.9,31,f,2721.83,0.000000,0.00,0.0000,0.0,INDIVIDUAL,139,0,NaN,NaN,592.215122,1
63760,1427850,14725,14725,14725.000000,36,BAT1327206,18.25,D,D3,nxtbook media,1,MORTGAGE,188000.00,Source Verified,home_improvement,pool,PA,16.33,0,0,34.0,11,0,110832,85.1,47,f,2970.54,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70,0,NaN,NaN,1302.373678,1
63771,273364,2000,2000,1800.000000,36,BAT1864701,7.37,A,A1,Retired,10,OWN,35000.00,Not Verified,vacation,Hawaii toMaui,CA,0.86,0,0,0.0,6,0,324,0.2,14,f,12.48,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4,0,NaN,NaN,1620.000000,1
63780,1268809,10000,10000,10000.000000,36,BAT1942645,12.69,B,B5,Comfort Keepers,2,RENT,52000.00,Not Verified,debt_consolidation,Family Loan,WA,7.04,0,0,32.0,9,0,6452,66.5,14,f,2071.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,97.022556,1
63806,1460508,4000,4000,4000.000000,36,BAT3372536,6.03,A,A1,snyder manufacturing inc.,10,OWN,35500.00,Not Verified,debt_consolidation,smartchoices,OH,24.41,0,0,30,7,0,4217,23.0,27,f,328.17,0.000000,0.00,0.0000,0.0,INDIVIDUAL,100,0,NaN,NaN,183.347826,1
63844,1662391,21000,21000,20725.000000,60,BAT3943761,19.72,D,D5,Farmers Insurance,5,RENT,85000.00,Verified,debt_consolidation,Consol,CA,14.61,0,0,30,7,0,17896,91.3,32,f,10766.48,0.000000,0.00,0.0000,0.0,INDIVIDUAL,183,0,NaN,NaN,196.013143,0
63846,949125,11525,11525,11500.000000,36,BAT4051248,5.42,A,A1,Deparment of Homeland Security,6,MORTGAGE,106800.00,Verified,home_improvement,Hot Tub,TX,8.08,0,0,30,8,0,8289,20.6,33,f,984.77,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,402.378641,1
63849,1269267,12400,12400,12400.000000,60,OTHERS,21.28,F,F2,Emerging Health MIT,7,RENT,50000.00,Source Verified,other,Unsecured Personal Loan,NY,15.77,1,1,12.0,13,0,4089,78.8,30,f,3787.11,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83,0,NaN,NaN,51.890863,1
63852,614439,7000,7000,7000.000000,36,BAT4786748,14.96,D,D2,Blue Cross Blue Shield of Massachusetts,7,RENT,36416.84,Not Verified,other,Getting back my life,MA,9.65,0,1,75.0,10,0,12392,73.8,17,f,1033.98,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,NaN,NaN,167.913279,0
63867,1470221,28000,28000,28000.000000,36,BAT3372536,7.62,A,A3,N.A,6,MORTGAGE,60000.00,Verified,debt_consolidation,Consolidation,NY,8.40,0,0,30,15,0,9367,21.1,27,f,3403.70,0.000000,0.00,0.0000,0.0,INDIVIDUAL,156,0,NaN,NaN,443.933649,1
63885,1190285,7500,7500,6450.000000,36,OTHERS,6.03,A,A1,gradea shoprite,10,MORTGAGE,95000.00,Verified,other,Personal Loan,CT,9.03,0,3,30,16,0,16538,7.2,46,f,584.11,0.000000,0.00,0.0000,0.0,INDIVIDUAL,91,0,NaN,NaN,2296.944444,1
63889,1672524,25000,25000,24975.000000,60,BAT1135695,21.98,E,E4,HomeMade Pizza Company,4,RENT,95000.00,Verified,debt_consolidation,credit card consolidation July 2012,IL,21.30,0,2,30,11,0,18315,92.5,27,f,14288.15,0.000000,0.00,0.0000,0.0,INDIVIDUAL,178,0,NaN,NaN,198.000000,0
63901,835461,1000,1000,1000.000000,36,BAT5458862,5.79,A,A2,Echelon properties,1,RENT,30000.00,Source Verified,major_purchase,Engine rebuild,CO,2.12,0,0,30,8,0,1178,3.6,12,f,69.76,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83,0,NaN,NaN,327.222222,1
63933,941766,5000,5000,4750.000000,36,BAT4051248,7.49,A,A4,Intermedix,4,MORTGAGE,26004.00,Not Verified,debt_consolidation,debtconsolidation,OK,20.49,0,0,30,8,0,3773,42.4,12,f,402.44,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70,0,NaN,NaN,88.985849,1
63940,1632382,18000,18000,18000.000000,60,BAT3943761,21.00,E,E2,Software Company,2,MORTGAGE,120000.00,Source Verified,credit_card,Refi several smaller payments,PA,17.09,1,1,21.0,13,0,1927,18.5,42,f,8895.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,152,0,NaN,NaN,104.162162,1
63942,1329785,21000,21000,21000.000000,36,BAT5046385,14.65,C,C3,DynCorp International,1,MORTGAGE,214596.00,Verified,other,personal loan,CA,13.89,0,2,30,16,0,64586,88.4,37,f,5074.96,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,730.610860,1
63951,980504,8000,8000,8000.000000,36,BAT1691418,8.49,A,A5,U.S. Dept. of Labor,3,RENT,36000.00,Source Verified,medical,New Beginings,AL,10.07,0,0,30,4,0,1777,24.0,11,f,1069.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,139,0,NaN,NaN,74.041667,1
63952,263557,1000,1000,800.000000,36,BAT1691418,10.08,B,B3,Guardian Industries,6,OWN,38000.00,Not Verified,major_purchase,Ready to Run Race Truck,MI,20.53,0,0,62.0,5,0,2308,46.2,25,f,103.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,69,0,NaN,NaN,49.956710,1
63966,1436231,16000,16000,16000.000000,36,BAT1327206,7.90,A,A4,hotel stanford,2,RENT,51000.00,Not Verified,major_purchase,Loan for Success,NY,22.27,0,0,30,16,0,28641,73.3,36,f,2022.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,390.736698,1
63988,980233,2000,2000,1975.000000,36,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17,0,NaN,NaN,91.161826,0
63989,823165,20000,20000,19950.000000,36,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,30,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,277.983193,1
63995,1363172,6000,6000,6000.000000,36,BAT47674,8.90,A,A5,ATT Prime Communications,2,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,30,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,NaN,NaN,79.914040,1

In [74]:
# tot_cur_bal

In [97]:
# total_rev_hi_lim
# revol_util
ch=[]
for i in df['total_rev_hi_lim']:
    j = str(i)
    ch.append(j)
df['total_rev_hi_lim'] = ch

sd=df['member_id'][df['total_rev_hi_lim'] == 'nan']

In [101]:

ch=[]
for i in df['revol_util']:
    j = float(i)
    ch.append(j)

In [102]:
df['revol_util'] = ch

In [114]:
ch=[]
for i in df['total_rev_hi_lim']:
    j = float(i)
    ch.append(j)

In [107]:
df['total_rev_hi_lim'] = ch

In [103]:
for i in sd:
    df['total_rev_hi_lim'][df['member_id']==i] = (((df['revol_bal'][df['member_id']==i])/(df['revol_util'][df['member_id']==i])))

/Users/zameershaik/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [121]:
df[df['total_rev_hi_lim'].isnull() == True]

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
1630,1600800,20000,20000,20000.000000,60,BAT3292317,16.29,C,C5,QinetiQ North America,6,RENT,115000.00,Verified,house,House Down Payment,MD,23.38,0,3,34.0,6,0,0,0.0,21,f,1837.01,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31,0,NaN,NaN,NaN,1
1753,690565,7000,7000,6975.000000,60,OTHERS,18.67,F,F2,Thomas McKean High School,4,RENT,27000.00,Source Verified,other,Haiti,DE,4.62,0,1,74.0,5,0,0,0.0,12,f,0.00,0.000000,1978.88,692.5900,0.0,INDIVIDUAL,NA,0,NaN,NaN,NaN,0
2460,253715,4500,4500,1575.000000,36,BAT3275209,8.63,A,A5,Central Washington Hospital,2,OWN,10000.00,Not Verified,car,I need a car,WA,0.00,1,0,23.0,5,0,0,0.0,6,f,595.65,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135,0,NaN,NaN,NaN,1
2963,701427,3000,3000,3000.000000,36,BAT1521494,14.72,C,C5,Jacobi Hospital,2,RENT,45996.00,Source Verified,other,Moving expense,NY,4.70,3,1,7.0,7,0,0,0.0,11,f,695.03,29.944975,44.48,0.6300,0.0,INDIVIDUAL,126,0,NaN,NaN,NaN,0
3176,810781,3375,3375,3375.000000,36,BAT1586599,14.83,D,D3,BAE Systems,10,MORTGAGE,45000.00,Verified,home_improvement,Fence,NC,0.00,0,1,66.0,2,0,0,0.0,8,f,824.21,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
3408,1407887,6000,6000,6000.000000,36,BAT1327206,7.90,A,A4,children of america,2,RENT,20000.00,Source Verified,credit_card,debt consolidation,PA,1.00,1,2,22.0,6,0,0,0.0,9,f,758.17,0.000000,0.00,0.0000,0.0,INDIVIDUAL,156,0,NaN,NaN,NaN,1
3517,659341,4000,4000,4000.000000,36,BAT2333412,15.33,D,D3,KC Engineering and Land Surveying,10,RENT,60000.00,Verified,other,Joe's Personal Loan,NY,9.96,0,0,34.0,2,0,0,0.0,10,f,1014.54,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
4121,903810,5000,5000,5000.000000,60,BAT20678,15.65,D,D4,pan american tool corp,10,MORTGAGE,58800.00,Not Verified,car,honda,FL,9.39,2,0,8.0,3,0,0,0.0,23,f,2090.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,200,0,NaN,NaN,NaN,1
4249,1310923,1000,1000,1000.000000,36,BAT5046385,19.03,E,E2,United,6,OWN,31800.00,Not Verified,other,Car Repair,HI,21.85,0,0,30,2,0,0,0.0,4,f,263.73,0.000000,70.07,0.7007,0.0,INDIVIDUAL,96,0,NaN,NaN,NaN,0
4610,900733,11000,11000,10975.000000,60,OTHERS,11.11,B,B5,H-S-P,6,MORTGAGE,75000.00,Not Verified,home_improvement,NEW ROOF,NJ,16.02,0,2,30,10,0,0,0.0,22,f,3356.69,0.000000,0.00,0.0000,0.0,INDIVIDUAL,252,0,NaN,NaN,NaN,0
6070,1201267,9000,9000,9000.000000,36,OTHERS,9.91,B,B1,Lion Sleep Labs,1,OWN,60000.00,Source Verified,car,Ural motorcycle loan,IL,8.88,0,2,52.0,4,0,0,0.0,18,f,1404.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135,0,NaN,NaN,NaN,1
6139,1404059,10000,10000,10000.000000,36,BAT1327206,7.62,A,A3,Eastern Numismatics Inc,10,MORTGAGE,175000.00,Source Verified,debt_consolidation,Discover Card Pay off,NY,11.23,0,1,70.0,10,0,0,0.0,28,f,1213.28,0.000000,0.00,0.0000,0.0,INDIVIDUAL,156,0,NaN,NaN,NaN,1
7545,687133,6500,6500,6500.000000,36,BAT5540558,13.98,C,C3,Hilmar Cheese Company,4,MORTGAGE,55000.00,Source Verified,credit_card,Pay of Bills,CA,11.91,0,2,46.0,8,0,0,0.0,15,f,1492.01,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
9633,799421,8000,4925,4568.354490,36,BAT1273836,6.17,A,A3,N.A,6,MORTGAGE,30000.00,Not Verified,major_purchase,File,NY,0.00,0,1,30,11,0,0,0.0,16,f,440.74,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113,0,NaN,NaN,NaN,1
9958,856061,12000,12000,12000.000000,60,BAT1184694,18.25,F,F1,Lee County Board of Commissioners,1,RENT,50400.00,Source Verified,wedding,Wedding Loan,FL,8.21,2,3,21.0,3,0,0,0.0,8,f,4498.70,0.000000,0.00,0.0000,0.0,INDIVIDUAL,130,0,NaN,NaN,NaN,1
10504,636813,6500,6500,5500.000000,36,BAT2881453,11.36,B,B5,Southeastern Freigt Lines,1,RENT,24000.00,Not Verified,other,Gas Saving Motorcycle Loan,TX,1.25,0,2,30,2,0,0,0.0,6,f,1142.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,148,0,NaN,NaN,NaN,1
10978,1108421,12000,12000,12000.000000,36,OTHERS,16.77,D,D2,bsw inc,1,MORTGAGE,44004.00,Verified,home_improvement,Home Improvement,MT,14.29,0,2,45.0,6,0,0,0.0,11,f,2787.98,0.000000,768.31,7.6831,0.0,INDIVIDUAL,104,0,NaN,NaN,NaN,0
12257,632748,5600,5600,5575.000000,36,OTHERS,13.48,C,C3,N.A,6,RENT,11688.00,Not Verified,small_business,online business loan,MT,0.00,0,0,32.0,2,0,0,0.0,11,f,994.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96,0,NaN,NaN,NaN,1
12364,1231334,7450,7450,7450.000000,36,BAT1942645,12.69,B,B5,HUB International Insurance Services,1,MORTGAGE,95000.00,Source Verified,wedding,wedding,CO,6.61,0,1,40.0,13,0,0,0.0,40,f,266.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30,0,NaN,NaN,NaN,1
16310,916142,1200,1200,1200.000000,36,OTHERS,7.29,A,A4,Pioneer Playhouse,4,RENT,19200.00,Source Verified,house,Rent,KY,25.50,0,0,30,8,0,0,0.0,10,f,27.98,0.000000,147.96,26.6328,0.0,INDIVIDUAL,17,0,NaN,NaN,NaN,0
17906,129893,8000,8000,2475.000000,36,BAT4160421,8.07,A,A4,N.A,3,RENT,54000.00,Not Verified,credit_card,Financially Stable Borrower,IL,10.44,0,1,0.0,20,0,0,0.0,42,f,110.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,NaN,NaN,NaN,1
17961,718672,10000,10000,9475.000000,36,BAT2974007,11.86,B,B5,"Pawhuska Hospital, Inc.",1,OWN,40000.00,Source Verified,debt_consolidation,My One Payment,OK,1.83,0,0,30,2,0,0,0.0,11,f,1643.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,100,0,NaN,NaN,NaN,1
19133,543543,15000,15000,14825.000000,36,BAT4271519,11.83,B,B3,Food Lion,7,MORTGAGE,36000.00,Not Verified,home_improvement,Home improvement,VA,12.27,0,2,69.0,6,0,0,0.0,17,f,2886.23,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
20114,968273,12000,12000,11975.000000,60,OTHERS,20.25,F,F1,Becton and Dickenson,1,MORTGAGE,62000.00,Not Verified,debt_consolidation,Last of my bills to pay off,WI,4.80,0,0,41.0,4,0,0,0.0,9,f,3138.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74,0,NaN,NaN,NaN,1
20572,814192,15000,15000,14500.000000,36,OTHERS,9.62,B,B3,Edward Rose & Sons,2,RENT,29040.00,Verified,home_improvement,Solving the Catch 22: Foreclosure Fix Up,MI,0.00,0,3,30,4,0,0,0.0,5,f,1410.29,0.000000,0.00,0.0000,0.0,INDIVIDUAL,65,0,NaN,NaN,NaN,1
20589,1261429,3000,3000,2900.000000,36,BAT1942645,7.51,A,A3,Minerva Biotechnologies,2,RENT,15000.00,Not Verified,other,Personal Loan,NY,17.68,0,1,30,10,0,0,0.0,13,f,103.28,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39,0,NaN,NaN,NaN,1
21683,1463768,20000,20000,20000.000000,60,BAT3372536,13.67,B,B5,JW Wireline,6,MORTGAGE,140000.00,Verified,home_improvement,Metal shop,TX,11.08,0,1,49.0,7,0,0,0.0,21,f,7119.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,196,0,NaN,NaN,NaN,0
21829,1245690,10000,10000,9975.000000,36,BAT1942645,6.62,A,A2,HealthSouth Rehab Hospital,1,MORTGAGE,75000.00,Verified,small_business,Business Loan,AL,26.61,0,0,30,12,0,0,0.0,38,f,574.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,NaN,NaN,NaN,1
21861,636920,10000,10000,9925.000000,36,BAT2881453,10.62,B,B3,Tillamook County,10,MORTGAGE,55000.00,Not Verified,other,Seeking Phoenix,OR,12.98,0,0,32.0,8,0,0,0.0,27,f,1254.69,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83,0,NaN,NaN,NaN,1
22922,630927,6000,6000,5000.000000,36,BAT2881453,10.62,B,B3,Aqua Care Pool Service,5,MORTGAGE,40000.00,Not Verified,home_improvement,Home Improvement/moving $$$ to accept a better...,TX,4.11,0,0,30,3,0,0,0.0,10,f,805.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,100,0,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35910,652909,3600,3600,3600.000000,36,BAT3260421,10.25,B,B2,University of Alabama at Birmingham Hosp,15,MORTGAGE,675048.00,Not Verified,other,Heat Pump Payoff,AL,1.55,0,4,25.0,8,0,0,0.0,25,f,601.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
36465,1089981,2000,2000,2000.000000,36,OTHERS,5.42,A,A1,N.A,10,RENT,30000.00,Not Verified,debt_consolidation,A Family Reunion...In Ireland.,NY,3.60,0,0,72.0,7,0,0,0.0,15,f,161.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,126,0,NaN,NaN,NaN,1
37188,1015816,10000,10000,10000.000000,36,BAT4271519,8.49,A,A5,N.A,5,MORTGAGE,108288.00,Source Verified,other,Second Mortgage Payoff,SC,2.76,0,0,30,3,0,0,0.0,7,f,1357.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
37416,963524,20000,20000,20000.000000,60,OTHERS,20.25,F,F1,N.A,6,MORTGAGE,82102.32,Source Verified,home_improvement,driveway/fence,TX,0.29,0,2,52.0,2,0,0,0.0,19,f,3217.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48,0,NaN,NaN,NaN,1
39118,165207,1800,1800,674.997450,36,BAT4939736,12.17,D,D2,Reiss Ltd.,1,RENT,42000.00,Not Verified,debt_consolidation,Loan for debt consolidation,NY,1.71,0,2,46.0,3,0,0,0.0,9,f,296.66,0.000000,36.02,0.4200,0.0,INDIVIDUAL,100,0,NaN,NaN,NaN,0
39427,434904,3250,3250,3250.000000,36,BAT5489674,16.63,E,E4,RR Donelly,1,OWN,8000.00,Not Verified,small_business,Small Business Partnership Loan,WI,6.30,0,2,30,5,0,0,0.0,6,f,896.53,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
40061,1006393,3500,3500,3500.000000,36,BAT5877328,8.49,A,A5,"Moore Group, Inc",10,MORTGAGE,42000.00,Not Verified,vacation,Disney,KY,22.09,0,0,30,2,0,0,0.0,8,f,472.64,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
42462,457316,15000,15000,6600.000000,36,BAT4935307,11.26,B,B2,Advent Global Solutions,1,OWN,70000.00,Source Verified,small_business,Purchasing Existing Profitable Business,TX,13.39,0,0,30,5,0,0,0.0,20,f,1563.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,56,0,NaN,NaN,NaN,1
42560,822820,2500,2500,2500.000000,36,BAT4351734,9.62,B,B3,N.A,1,RENT,48000.00,Not Verified,wedding,Kids growing up fast,NV,13.75,0,0,61.0,2,0,0,0.0,26,f,389.07,44.920843,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
44517,1581015,16000,16000,16000.000000,60,BAT3292317,16.29,C,C5,Brookville Equipment Corp.,6,OWN,45000.00,Verified,major_purchase,purchase,PA,6.83,0,1,30,3,0,0,0.0,15,f,4330.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,100,0,NaN,NaN,NaN,1
45392,1376573,30000,30000,29950.000000,36,BAT47674,11.71,B,B3,U.S. Army,5,RENT,65000.00,Verified,wedding,Fund wedding and associated costs,TX,18.37,0,0,29.0,7,0,0,0.0,10,f,5618.93,0.000000,0.00,0.0000,0.0,INDIVIDUAL,143,0,NaN,NaN,NaN,1
46617,586290,4200,4200,4200.000000,36,BAT3157685,11.83,B,B3,Wells Fargo,1,RENT,10800.00,Not Verified,moving,Moving expenses for San Diego,CA,0.00,0,2,30,3,0,0,0.0,10,f,806.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
48114,134920,23400,23400,15550.000000,36,BAT3275209,18.29,G,G4,Stordok Document Destruction/Moreno Roofing Co.,10,MORTGAGE,75000.00,Not Verified,credit_card,Temporary small business loan,CA,8.54,0,2,41.0,5,0,0,0.0,28,f,7164.77,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
48479,1599947,6450,6450,6450.000000,36,OTHERS,10.16,B,B1,we heart beer LLC,3,RENT,48000.00,Not Verified,home_improvement,credit builder,TX,6.85,0,2,30,3,0,0,0.0,9,f,258.88,0.000000,325.49,3.0800,0.0,INDIVIDUAL,22,0,NaN,NaN,NaN,0
48558,1352794,7700,7700,7700.000000,36,BAT5046385,7.90,A,A4,City of Arlington,10,MORTGAGE,32148.68,Source Verified,home_improvement,Home Improvement Loan,TX,0.00,0,0,30,2,0,0,0.0,7,f,972.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
49676,1312226,1800,1800,1800.000000,36,OTHERS,14.27,C,C2,Pequea Machine.inc,9,RENT,33600.00,Not Verified,car,Car,PA,6.43,0,0,24.0,2,0,0,0.0,15,f,421.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
49757,1085611,3300,3300,3300.000000,36,BAT1914408,6.99,A,A3,American transport group,1,RENT,40000.00,Not Verified,other,New car,IL,20.04,0,2,30,10,0,0,0.0,16,f,363.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,143,0,NaN,NaN,NaN,1
49779,919268,5000,5000,5000.000000,36,BAT20678,7.29,A,A4,carolina thomas,6,MORTGAGE,48996.00,Not Verified,home_improvement,Home Improvement Loan,NC,0.00,0,0,30,4,0,0,0.0,20,f,580.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
51234,630127,10000,10000,9000.000000,36,BAT2881453,7.51,A,A4,Ochsner clinc,8,MORTGAGE,39000.00,Not Verified,major_purchase,NONE,LA,0.00,0,0,30,9,0,0,0.0,32,f,1196.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
51568,163835,500,500,400.000000,36,BAT4939736,8.07,A,A4,N.A,1,RENT,18000.00,Not Verified,other,buying a new computer,NY,4.27,0,0,0.0,4,0,0,0.0,4,f,64.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,NaN,NaN,NaN,1
54787,679527,4500,4500,4000.000000,36,BAT1521494,7.14,A,A3,N.A,1,MORTGAGE,55000.00,Not Verified,small_business,Loan 4.5k,MD,9.47,0,1,82.0,7,0,0,0.0,21,f,488.61,0.000000,0.00,0.0000,0.0,INDIVIDUAL,126,0,NaN,NaN,NaN,1
56146,1309623,2600,2600,2600.000000,36,OTHERS,12.42,B,B4,Christman Fuel Supply,9,MORTGAGE,33600.00,Not Verified,car,Mercedes,NY,0.00,0,0,34.0,2,0,0,0.0,21,f,78.94,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,NaN,NaN,NaN,1
56528,879649,10000,10000,9975.000000,60,BAT2078974,19.74,F,F5,N.A,6,MORTGAGE,69600.00,Source Verified,home_improvement,Home Improvement,NC,9.02,0,3,30.0,3,0,0,0.0,18,f,5769.69,0.000000,0.00,0.0000,0.0,INDIVIDUAL,252,0,NaN,NaN,NaN,0
56978,755610,20500,20500,19250.000000,60,OTHERS,13.98,C,C3,r.r. donnelley & Sons Inc,10,OWN,60000.00,Verified,moving,Moving Expences,PA,12.58,0,1,30,4,0,0,0.0,22,f,457.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,NaN,NaN,NaN,1
59719,1235314,6500,6500,6500.000000,36,BAT1942645,10.65,B,B2,Donovan Hatem LLP,2,MORTGAGE,56650.00,Not Verified,debt_consolidation,Loan Consolidation,MA,0.00,0,2,30,2,0,0,0.0,7,f,765.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74,0,NaN,NaN,NaN,1
59822,1357534,24000,24000,23975.000000,60,OTHERS,24.11,G,G5,Stryker Instruments,10,MORTGAGE,56000.00,Verified,home_improvement,Home Impovements,MI,11.96,0,3,56.0,4,0,0,0.0,19,f,2828.69,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,NaN,NaN,NaN,1
60539,906246,21000,21000,20975.000000,60,BAT5320519,14.91,D,D2,Covenant Aviation LLC,4,RENT,41721.60,Verified,debt_consolidation,Family Bills,CA,9.64,1,1,22.0,10,0,0,0.0,13,f,5760.88,24.914000,832.81,8.3400,0.0,INDIVIDUAL,118,0,NaN,NaN,NaN,0
61061,886231,5000,5000,4975.000000,36,BAT5320519,6.92,A,A3,Bureau of Prision,10,MORTGAGE,60000.00,Source Verified,home_improvement,Home Improvement Loan,FL,6.52,0,1,30,14,0,0,0.0,29,f,277.26,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48,0,NaN,NaN,NaN,1
62637,723407,2000,2000,2000.000000,36,BAT2974007,13.61,C,C2,PA Dept. of Corrections,1,MORTGAGE,32000.00,Verified,other,melchora,PA,15.41,0,0,48.0,5,0,0,0.0,10,f,445.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,NaN,1
62917,407280,5000,5000,1186.385394,36,BAT4734809,13.47,C,C4,United Health Group,1,MORTGAGE,65004.00,Not Verified,wedding,my loan,TX,18.92,3,1,2.0,7,0,0,0.0,24,f,964.11,0.000000,0.00,0.0000,0.0,INDIVIDUAL,108,0,NaN,NaN,NaN,1

In [123]:
df['total_rev_hi_lim'].fillna(0,inplace=True)

In [127]:
dfmain = df

In [128]:
df

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,batch_enrolled,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,purpose,title,addr_state,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,collections_12_mths_ex_med,application_type,last_week_pay,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,loan_status
0,58189336,14350,14350,14350.0,36,OTHERS,19.19,E,E3,clerk,9,OWN,28700.00,Source Verified,debt_consolidation,Debt consolidation,FL,33.88,0,1,50.0,14,1,22515,73.1,28,f,1173.84,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,28699.0,30800.000000,0
1,70011223,4800,4800,4800.0,36,BAT1586599,10.99,B,B4,Human Resources Specialist,1,MORTGAGE,65000.00,Source Verified,home_improvement,Home improvement,MD,3.64,0,1,30,6,0,7624,23.2,13,w,83.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9,0,0.0,9974.0,32900.000000,0
2,70255675,10000,10000,10000.0,36,BAT1586599,7.26,A,A4,Driver,2,OWN,45000.00,Not Verified,debt_consolidation,Debt consolidation,OH,18.42,0,0,30,5,0,10877,31.2,19,w,56.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,9,0,65.0,38295.0,34900.000000,0
3,1893936,15000,15000,15000.0,36,BAT4808022,19.72,D,D5,Us office of Personnel Management,10,RENT,105000.00,Not Verified,debt_consolidation,Debt consolidation,VA,14.97,0,2,46.0,10,0,13712,55.5,21,f,4858.62,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135,0,0.0,55564.0,24700.000000,0
4,7652106,16000,16000,16000.0,36,BAT2833642,10.64,B,B2,LAUSD-HOLLYWOOD HIGH SCHOOL,10,RENT,52000.00,Verified,credit_card,refi,CA,20.16,0,0,30,11,0,35835,76.2,27,w,2296.41,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96,0,0.0,47159.0,47033.000000,0
5,10247268,15000,15000,14950.0,36,BAT2575549,8.90,A,A5,Design Consultant,2,MORTGAGE,120000.00,Not Verified,debt_consolidation,Credit Card Debt Consolidation,IN,12.30,0,0,56.0,18,0,19040,64.5,30,f,1957.24,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113,0,0.0,350619.0,29500.000000,0
6,8089625,5000,5000,4975.0,36,OTHERS,7.90,A,A4,TOYOTA OF NORTH HOLLYWOOD,5,RENT,75000.00,Source Verified,debt_consolidation,PAY THEM OFF,CA,5.70,0,0,30,13,2,13272,23.9,23,f,578.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,117,0,1023.0,13272.0,55500.000000,1
7,23043116,6000,6000,6000.0,36,OTHERS,9.17,B,B1,Banker,8,MORTGAGE,54000.00,Not Verified,credit_card,Credit card refinancing,AL,11.63,0,1,46.0,13,0,3484,29.5,49,f,637.51,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,0.0,272579.0,11800.000000,0
8,45900933,6000,6000,6000.0,36,BAT4136152,13.99,C,C4,LVN,7,MORTGAGE,92000.00,Not Verified,home_improvement,Home improvement,CA,30.85,0,0,77.0,16,0,47567,76.6,27,w,621.72,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44,0,0.0,281521.0,62100.000000,0
9,41272507,34550,34550,34550.0,60,BAT4694572,17.14,D,D4,Registered Nurse,2,MORTGAGE,72000.00,Verified,debt_consolidation,Debt consolidation,KY,33.92,0,0,30,12,0,30040,90.5,30,w,5535.46,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52,0,0.0,76034.0,33200.000000,0
10,56621560,25000,25000,24975.0,36,OTHERS,13.33,C,C3,VP of Operations,10,OWN,135000.00,Source Verified,credit_card,Credit card refinancing,NM,14.20,0,1,52.0,15,0,23893,50.8,32,f,1551.58,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,72193.0,47000.000000,0
11,4221941,15000,15000,15000.0,36,OTHERS,18.49,D,D2,Jp Morgan chase bank,4,RENT,76000.00,Verified,debt_consolidation,Loan to payoff credit card debt,CA,15.86,0,1,82.0,15,0,14085,71.9,30,f,3726.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,95,0,0.0,39152.0,19600.000000,1
12,43387539,18000,18000,18000.0,36,BAT5924421,6.99,A,A3,driver,7,MORTGAGE,62000.00,Not Verified,credit_card,Credit card refinancing,TN,18.58,0,2,30,15,0,47795,34.2,31,f,992.37,0.000000,0.00,0.0000,0.0,INDIVIDUAL,48,0,0.0,194011.0,139900.000000,0
13,23001903,9000,9000,9000.0,36,BAT3193689,6.03,A,A1,Federal Law Enforcement,10,MORTGAGE,145000.00,Not Verified,credit_card,Credit card refinancing,TX,15.42,0,0,30,19,0,11685,27.2,39,f,633.42,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,0.0,165164.0,43000.000000,0
14,13670372,8800,8800,8800.0,36,BAT224923,13.65,C,C1,Truck Driver,10,RENT,80000.00,Not Verified,debt_consolidation,Debt consolidation,CA,13.98,0,1,30,12,0,17060,41.4,17,w,1521.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,82,0,0.0,39634.0,41200.000000,1
15,49874851,8000,8000,8000.0,36,BAT1184694,15.61,D,D1,ASSISTANT QAPI COORDINATOR,4,RENT,50000.00,Source Verified,debt_consolidation,Debt consolidation,CA,27.39,0,2,30,14,0,6544,35.4,24,f,801.55,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35,0,0.0,48488.0,18500.000000,0
16,9878144,18450,18450,18450.0,60,BAT1930365,21.70,E,E2,LS1,9,RENT,69000.00,Source Verified,debt_consolidation,Debt Consolidation,CA,24.28,0,0,72.0,13,0,15297,96.2,35,f,6269.20,0.000000,0.00,0.0000,0.0,INDIVIDUAL,96,0,0.0,71191.0,15900.000000,0
17,12866989,30750,30750,30700.0,36,OTHERS,16.99,D,D1,N.A,6,MORTGAGE,70000.00,Verified,credit_card,Credit card refinancing,PA,29.13,3,2,11.0,7,0,17299,99.4,35,f,7394.32,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104,0,0.0,221335.0,17400.000000,0
18,58568833,9000,9000,9000.0,36,BAT3873588,9.99,B,B3,Production employee,7,RENT,60000.00,Source Verified,debt_consolidation,Debt consolidation,KS,19.70,0,0,30,9,0,9305,54.7,28,f,412.36,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,34538.0,17000.000000,0
19,62725253,24000,24000,24000.0,36,BAT3873588,10.99,B,B4,Principal Consultant,7,RENT,130000.00,Verified,debt_consolidation,Debt consolidation,IL,23.22,0,1,56.0,16,0,23770,76.7,25,w,833.27,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,125903.0,31000.000000,0
20,66791957,20000,20000,20000.0,60,BAT2252229,17.86,D,D5,Zone business manager,9,RENT,96000.00,Not Verified,debt_consolidation,Debt consolidation,FL,18.31,1,0,18.0,11,0,18680,68.7,28,w,843.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,0.0,66738.0,27200.000000,0
21,1699807,12400,12400,12400.0,36,BAT1135695,6.62,A,A2,Expeditors,2,OWN,40000.00,Not Verified,debt_consolidation,Debt consolidation,NY,20.31,0,2,28.0,6,0,1804,12.2,9,f,0.00,0.000000,712.76,7.0300,0.0,INDIVIDUAL,NA,0,NaN,NaN,14786.885246,0
22,54486146,4200,4200,4200.0,36,OTHERS,17.57,D,D4,production coordinator,10,MORTGAGE,46000.00,Not Verified,debt_consolidation,Debt consolidation,CA,31.25,1,0,20.0,14,0,21174,82.4,28,w,394.08,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31,0,0.0,282808.0,25700.000000,0
23,41408977,10500,10500,10500.0,36,BAT4694572,13.66,C,C3,Title Manager,7,OWN,60000.00,Source Verified,debt_consolidation,Debt consolidation,MO,13.82,0,1,30,7,0,8661,60.6,24,f,845.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,30,0,0.0,71697.0,14300.000000,1
24,63047232,16000,16000,16000.0,36,BAT4271519,7.89,A,A5,Coordinator,1,RENT,65000.00,Source Verified,debt_consolidation,Debt consolidation,FL,21.54,0,0,30,9,0,22438,54.2,30,w,398.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,147448.0,41400.000000,0
25,22741274,23800,23800,23800.0,60,OTHERS,15.61,D,D1,Quality Engineer,4,MORTGAGE,70000.00,Source Verified,debt_consolidation,Debt consolidation,NC,21.93,0,0,30,13,0,20253,46.7,27,f,5008.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,0.0,327930.0,43400.000000,0
26,17563299,7200,7200,7150.0,36,OTHERS,12.99,C,C1,Top shelf sales,2,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,TX,13.43,0,0,73.0,11,1,6392,32.0,28,f,1047.06,0.000000,0.00,0.0000,0.0,INDIVIDUAL,70,0,0.0,8589.0,19800.000000,1
27,10317534,19200,19200,19175.0,36,OTHERS,6.62,A,A2,Physician,1,MORTGAGE,250000.00,Source Verified,debt_consolidation,Close cards and consolidate,AL,25.86,0,1,30,9,0,28912,87.3,23,f,1785.13,0.000000,0.00,0.0000,0.0,INDIVIDUAL,104,0,0.0,447388.0,33100.000000,1
28,50609137,15000,15000,15000.0,36,BAT1184694,6.92,A,A4,Teacher,3,MORTGAGE,90000.00,Verified,debt_consolidation,Debt consolidation,TX,29.68,0,1,30,16,0,24129,48.4,31,w,624.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35,0,0.0,114298.0,49900.000000,0
29,70008968,4000,4000,4000.0,36,BAT1586599,17.57,D,D4,cna,2,MORTGAGE,20000.00,Verified,other,Other,NJ,30.79,0,0,30,9,0,6336,58.1,9,f,52.71,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4,0,0.0,31445.0,10900.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63969,47417289,13800,13800,13800.0,60,BAT1104812,18.84,E,E2,Manager,5,RENT,114000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.56,0,2,68.0,26,0,19210,40.7,45,f,1853.34,0.000000,0.00,0.0000,0.0,INDIVIDUAL,39,0,0.0,157141.0,47200.000000,0
63970,6039679,21725,21725,21725.0,60,OTHERS,17.77,D,D1,ECC,3,MORTGAGE,68000.00,Verified,debt_consolidation,Pool,MA,10.34,0,1,30.0,7,1,2207,29.0,15,f,7615.40,0.000000,0.00,0.0000,0.0,INDIVIDUAL,122,0,56.0,296940.0,7600.000000,1
63971,65437502,2500,2500,2500.0,36,BAT2252229,6.89,A,A3,CONSTRUCTION COORDINATOR,1,MORTGAGE,100000.00,Not Verified,medical,Medical expenses,CA,3.31,0,0,30,16,0,9642,14.4,27,w,41.02,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,1428.0,294013.0,67100.000000,0
63972,63622981,17200,17200,17200.0,60,BAT4271519,17.57,D,D4,Vocational Counselor,10,RENT,43008.00,Not Verified,debt_consolidation,Debt consolidation,MO,19.50,0,0,30,12,1,22175,75.7,41,w,949.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,150815.0,29300.000000,0
63973,19868235,35000,35000,35000.0,60,BAT4271519,17.57,D,D4,Securities broker,8,MORTGAGE,250000.00,Source Verified,debt_consolidation,Debt consolidation,AR,13.18,2,1,3.0,12,0,30422,93.9,55,w,8733.80,0.000000,0.00,0.0000,0.0,INDIVIDUAL,83,0,0.0,632686.0,32400.000000,0
63974,7647338,24000,24000,24000.0,36,BAT2833642,13.05,B,B5,New York Life Insurance Company,3,RENT,74000.00,Verified,debt_consolidation,Debt consolidation,NY,18.40,0,0,30,16,0,35689,76.4,31,f,4951.89,0.000000,0.00,0.0000,0.0,INDIVIDUAL,131,0,0.0,43946.0,46702.000000,0
63975,1890604,15000,15000,15000.0,36,OTHERS,12.12,B,B3,Comforce Telecom,10,MORTGAGE,63300.00,Verified,debt_consolidation,Credit Card Consolidation,FL,27.51,0,0,30,17,0,17999,73.8,30,f,2966.66,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,0.0,231063.0,24400.000000,1
63976,16460359,18000,18000,18000.0,36,OTHERS,12.99,B,B5,Process Operator,7,MORTGAGE,80000.00,Source Verified,debt_consolidation,Debt consolidation,IN,9.44,0,0,57.0,7,0,7319,81.3,20,w,1742.12,0.000000,0.00,0.0000,0.0,INDIVIDUAL,44,0,0.0,57125.0,9000.000000,0
63977,70619458,21200,21200,21200.0,60,BAT2803411,15.41,D,D1,Vice President mortgage sales,2,MORTGAGE,75000.00,Source Verified,debt_consolidation,Debt consolidation,TN,24.21,2,2,12.0,13,1,7977,68.2,28,w,254.09,0.000000,0.00,0.0000,0.0,INDIVIDUAL,4,0,0.0,88497.0,11700.000000,0
63978,58837067,9000,9000,9000.0,36,BAT3873588,9.17,B,B2,Nurse,8,MORTGAGE,88000.00,Not Verified,home_improvement,Home improvement,AR,17.52,0,1,36.0,24,0,7187,35.8,37,f,382.81,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,194.0,223720.0,20100.000000,0
63979,35643212,6000,6000,6000.0,36,OTHERS,13.35,C,C2,Nurse,10,RENT,60000.00,Not Verified,debt_consolidation,Debt consolidation,FL,24.68,0,0,30,13,0,20395,85.3,20,w,785.59,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,0.0,40418.0,23900.000000,0
63980,55478345,3000,3000,3000.0,36,OTHERS,15.61,D,D1,Patient account rep,8,MORTGAGE,43000.00,Verified,debt_consolidation,Debt consolidation,MN,20.76,1,1,nan,10,1,5229,65.0,34,f,218.47,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,26144.0,8100.000000,0
63981,54007397,12800,12800,12800.0,36,BAT3726927,9.99,B,B3,Pre-k teacher and assistant director,4,MORTGAGE,109000.00,Not Verified,debt_consolidation,Debt consolidation,CT,10.28,0,0,30,15,0,30253,63.6,19,w,679.26,20.650000,0.00,0.0000,0.0,INDIVIDUAL,31,0,0.0,30253.0,47600.000000,0
63982,37016622,15000,15000,15000.0,36,BAT2558388,12.39,C,C1,Research Scientist,4,RENT,71000.00,Not Verified,debt_consolidation,Debt consolidation,CA,16.41,0,0,30,7,0,19321,94.2,10,f,1818.88,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,0.0,28156.0,20500.000000,0
63983,26507802,34875,34875,34625.0,36,BAT2558388,15.61,D,D1,N.A,6,MORTGAGE,79384.56,Source Verified,debt_consolidation,Debt consolidation,SC,31.29,0,0,30,17,1,21890,54.3,29,f,5853.82,0.000000,0.00,0.0000,0.0,INDIVIDUAL,74,0,1849.0,229007.0,40300.000000,0
63984,1478303,7500,7500,7500.0,36,BAT2575549,14.30,C,C1,Technical Support,1,RENT,35000.00,Verified,credit_card,Debt Consolidation,TX,15.22,0,2,30,4,0,16822,42.8,8,w,1606.35,0.000000,0.00,0.0000,0.0,INDIVIDUAL,113,0,0.0,19572.0,39300.000000,0
63985,62374014,27500,27500,27500.0,60,BAT1780517,13.33,C,C3,SUPERVISOR,1,RENT,55000.00,Source Verified,credit_card,Credit card refinancing,CA,12.46,0,0,30,6,0,26926,56.0,17,w,1179.73,0.000000,0.00,0.0000,0.0,INDIVIDUAL,17,0,0.0,26926.0,48100.000000,0
63986,55289340,12050,12050,12050.0,60,OTHERS,23.99,F,F3,Assistant Project Director,6,OWN,37000.00,Source Verified,debt_consolidation,Debt consolidation,NJ,24.78,0,1,30,11,0,8797,53.3,13,f,1608.30,0.000000,0.00,0.0000,0.0,INDIVIDUAL,31,0,0.0,36695.0,16500.000000,0
63987,9177047,5600,5600,5600.0,36,OTHERS,11.99,B,B3,N.A,9,RENT,65000.00,Verified,debt_consolidation,Bye bye Debt!,CA,7.09,0,0,79.0,6,0,4186,60.7,16,f,977.49,0.000000,0.00,0.0000,0.0,INDIVIDUAL,109,0,0.0,7891.0,6900.000000,0
63988,980233,2000,2000,1975.0,36,BAT1691418,5.99,A,A2,KELLYS HARDWARE,1,RENT,19200.00,Not Verified,other,BILLS,AR,2.06,0,0,55.0,5,0,2197,24.1,21,f,38.38,14.990138,364.26,74.9336,0.0,INDIVIDUAL,17,0,NaN,NaN,91.161826,0
63989,823165,20000,20000,19950.0,36,BAT5458862,17.43,E,E5,Newton-Wellesley Hospital,10,MORTGAGE,101000.00,Verified,debt_consolidation,credit card payoff,MA,14.91,0,0,30,14,0,23156,83.3,24,f,5810.87,0.000000,0.00,0.0000,0.0,INDIVIDUAL,157,0,NaN,NaN,277.983193,1
63990,2728636,18000,18000,18000.0,36,BAT5811547,8.90,A,A5,Creative Technology,10,MORTGAGE,160000.00,Source Verified,debt_consolidation,Get Rid Of Debt,OH,12.83,0,2,24.0,15,0,26275,62.6,31,f,2522.68,0.000000,0.00,0.0000,0.0,INDIVIDUAL,135,0,0.0,271843.0,42000.000000,1
63991,9397061,10000,10000,10000.0,36,BAT5811547,18.55,D,D2,Senior Estimator,10,RENT,40000.00,Not Verified,debt_consolidation,The Great Payoff,MO,18.69,0,1,57.0,11,0,10739,83.9,24,f,1629.50,0.000000,0.00,0.0000,0.0,INDIVIDUAL,52,0,94.0,21772.0,12800.000000,1
63992,51613614,28000,28000,28000.0,36,BAT1184694,15.61,D,D1,Account executive,2,RENT,148000.00,Source Verified,debt_consolidation,Debt consolidation,CA,7.07,0,0,30,8,0,26725,84.3,11,w,2538.33,0.000000,0.00,0.0000,0.0,INDIVIDUAL,35,0,0.0,35430.0,31700.000000,0
63993,37016497,1750,1750,1750.0,36,OTHERS,12.39,C,C1,Payroll and billing specialist,2,RENT,40000.00,Not Verified,debt_consolidation,Debt consolidation,IL,8.43,9,1,17.0,8,0,403,13.9,25,f,210.99,0.000000,0.00,0.0000,0.0,INDIVIDUAL,61,0,0.0,31906.0,2900.000000,0
63994,66009021,15000,15000,15000.0,36,BAT2252229,9.99,B,B3,Manager,1,RENT,60000.00,Source Verified,credit_card,Credit card refinancing,NJ,17.48,0,0,30,12,0,28561,71.9,19,w,357.31,0.000000,0.00,0.0000,0.0,INDIVIDUAL,13,0,0.0,28561.0,39700.000000,0
63995,1363172,6000,6000,6000.0,36,BAT47674,8.90,A,A5,ATT Prime Communications,2,RENT,42000.00,Source Verified,car,Car Loan,TX,12.09,0,2,30,5,0,2789,34.9,11,f,627.78,0.000000,0.00,0.0000,0.0,INDIVIDUAL,78,0,NaN,NaN,79.914040,1
63996,60869253,4200,4200,4200.0,36,BAT47674,6.24,A,A2,Account Executive,2,RENT,85000.00,Not Verified,major_purchase,Major purchase,CA,9.40,0,0,30,13,0,6990,13.7,23,w,102.18,0.000000,0.00,0.0000,0.0,INDIVIDUAL,22,0,0.0,34544.0,51200.000000,0
63997,55298262,10000,10000,10000.0,36,OTHERS,11.53,B,B5,Assistant instructor,3,RENT,27000.00,Not Verified,debt_consolidation,Debt consolidation,NJ,18.67,0,0,30,14,0,10585,45.0,18,w,535.95,0.000000,0.00,0.0000,0.0,INDIVIDUAL,26,0,0.0,21061.0,23500.000000,0
63998,2430978,12300,12300,12300.0,36,OTHERS,6.62,A,A2,Array Connector Corp,5,RENT,40000.00,Not Verified,home_improvement,LoanForGood_2012,FL,3.57,0,1,30,10,0,3148,7.7,19,f,1295.56,0.000000,0.00,0.0000,0.0,INDIVIDUAL,161,0,0.0,3148.0,40988.000000,1